/**
 * Expected schema states — migration-aware fingerprint registry
 * (WO-O4O-DATABASE-STATE-CLASSIFIER-SCHEMA-DRIFT-AND-CONNECTION-LOG-HARDENING-V1)
 *
 * One entry per reachable schema state:
 *   [0]   canonical baseline (no incremental migration applied)
 *   [k]   baseline + INCREMENTAL_MIGRATIONS[0..k-1]   (k = 1 .. INCREMENTAL_MIGRATIONS.length)
 *
 * The classifier compares the live fingerprint of every established database (BOOTSTRAPPED and
 * LEGACY_ESTABLISHED alike) with the entry for its current incremental prefix, and the migration
 * job re-fingerprints after applying migrations and compares with the final entry.
 *
 * Adding a migration (lockstep, enforced by scripts/db/check-migration-contract.mjs C22 and jest):
 *   1. register it in manifest.ts (import + append)
 *   2. bootstrap an ISOLATED PostgreSQL 15 database with `node dist/migrate.js` (or
 *      `pnpm --filter @o4o/api-server migration:run`) so the baseline + every incremental
 *      migration runs in sequence, then read the reported POST_MIGRATION fingerprint / line count
 *   3. append { appliedThrough: '<MigrationName>', fingerprint, fingerprintLineCount } here
 * Values are NEVER copied from a live database's fingerprint at runtime, never regenerated by CI,
 * and never adopted automatically on mismatch. A mismatch means investigate, not update.
 */

import { CANONICAL_SCHEMA_BASELINE_META } from '../bootstrap/canonical-schema-baseline.meta.js';

export interface ExpectedSchemaState {
  /** Name of the last incremental migration applied in this state; null = baseline only. */
  readonly appliedThrough: string | null;
  /** sha256 of the normalized fingerprint lines (see bootstrap/schema-fingerprint.ts). */
  readonly fingerprint: string;
  readonly fingerprintLineCount: number;
}

/** Append only. Entry k MUST correspond to INCREMENTAL_MIGRATIONS[k-1]. */
export const EXPECTED_SCHEMA_STATES: readonly ExpectedSchemaState[] = [
  {
    appliedThrough: null,
    fingerprint: CANONICAL_SCHEMA_BASELINE_META.expectedFingerprint,
    fingerprintLineCount: CANONICAL_SCHEMA_BASELINE_META.expectedFingerprintLineCount,
  },
  // WO-O4O-STORE-TABLET-LOCATION-CONTENT-RUNTIME-MANAGEMENT-V1 — computed in an isolated
  // PostgreSQL 15 (bootstrap + migration 1) and cross-checked read-only against production
  // (typeorm_migrations id 679) on 2026-09-15: identical hash and line count.
  {
    appliedThrough: 'CreateStoreTabletDevicesAndScreenSetDescription1789435443554',
    fingerprint: 'bbef95607b3f24ae61796f4e2042b01e171e1cb7ec6a8470f6c6f3963306d816',
    fingerprintLineCount: 5895,
  },
] as const;

/** Expected state after `prefixLength` incremental migrations; undefined when not registered. */
export function expectedSchemaStateFor(
  prefixLength: number,
  states: readonly ExpectedSchemaState[] = EXPECTED_SCHEMA_STATES,
): ExpectedSchemaState | undefined {
  if (!Number.isInteger(prefixLength) || prefixLength < 0) return undefined;
  return states[prefixLength];
}

/** Human label for a state (log lines). */
export function expectedSchemaStateLabel(state: ExpectedSchemaState | undefined): string {
  if (!state) return 'UNREGISTERED';
  return state.appliedThrough ?? `baseline ${CANONICAL_SCHEMA_BASELINE_META.baselineVersion}`;
}
