/**
 * Expected schema states — migration-aware fingerprint registry
 * (WO-O4O-DATABASE-STATE-CLASSIFIER-SCHEMA-DRIFT-AND-CONNECTION-LOG-HARDENING-V1)
 *
 * One entry per reachable schema state:
 *   [0]   canonical baseline (no incremental migration applied)
 *   [k]   baseline + INCREMENTAL_MIGRATIONS[0..k-1]   (k = 1 .. INCREMENTAL_MIGRATIONS.length)
 *
 * The classifier compares the live fingerprint of every established database (BOOTSTRAPPED and
 * LEGACY_ESTABLISHED alike) with the entry for its current incremental prefix, and the migration
 * job re-fingerprints after applying migrations and compares with the final entry.
 *
 * Adding a migration (lockstep, enforced by scripts/db/check-migration-contract.mjs C22 and jest):
 *   1. register it in manifest.ts (import + append)
 *   2. bootstrap an ISOLATED PostgreSQL 15 database with `node dist/migrate.js` (or
 *      `pnpm --filter @o4o/api-server migration:run`) so the baseline + every incremental
 *      migration runs in sequence, then read the reported POST_MIGRATION fingerprint / line count
 *   3. append { appliedThrough: '<MigrationName>', fingerprint, fingerprintLineCount } here
 * Values are NEVER copied from a live database's fingerprint at runtime, never regenerated by CI,
 * and never adopted automatically on mismatch. A mismatch means investigate, not update.
 */

import { CANONICAL_SCHEMA_BASELINE_META } from '../bootstrap/canonical-schema-baseline.meta.js';

export interface ExpectedSchemaState {
  /** Name of the last incremental migration applied in this state; null = baseline only. */
  readonly appliedThrough: string | null;
  /** sha256 of the normalized fingerprint lines (see bootstrap/schema-fingerprint.ts). */
  readonly fingerprint: string;
  readonly fingerprintLineCount: number;
}

/** Append only. Entry k MUST correspond to INCREMENTAL_MIGRATIONS[k-1]. */
export const EXPECTED_SCHEMA_STATES: readonly ExpectedSchemaState[] = [
  // Canonical baseline 2026-09-18-id685 — generated from an isolated PostgreSQL 15.17 built by the
  // previous baseline (2026-09-15-id678) + its 7 incremental migrations, verified read-only equal to the
  // production live fingerprint on 2026-09-18 (WO-O4O-RETIRED-SERVICE-MIGRATION-HISTORY-SQUASH-AND-BASELINE-FINAL-CLOSURE-V1).
  // The 7 former entries were absorbed into this baseline; new incremental states are appended below.
  {
    appliedThrough: null,
    fingerprint: CANONICAL_SCHEMA_BASELINE_META.expectedFingerprint,
    fingerprintLineCount: CANONICAL_SCHEMA_BASELINE_META.expectedFingerprintLineCount,
  },
  // WO-O4O-STORE-OWNER-AGREEMENT-PUBLISH-PREREQUISITES-V1 — store_owner_termination_cases.
  // baseline 2026-09-18-id685 fresh bootstrap + incremental 1 을 격리 PostgreSQL 15 에서
  // 산출(baseline id678 + incrementals 1..8 과 동일 최종 스키마): 운영 DB fingerprint 채택 아님.
  {
    appliedThrough: 'CreateStoreOwnerTerminationCases1789701000000',
    fingerprint: '73d74984bd0448560639742fcce3c8922295f6b967f8bd71dd28f352552756d0',
    fingerprintLineCount: 5771,
  },
  // WO-O4O-UNIFIED-STORE-WORKSPACE-FOUNDATION-V1 §8-1 — handoff_tokens target_service_key NULL 허용 +
  // target_workspace varchar(32) + CHK_handoff_tokens_target_kind. baseline 2026-09-18-id685 fresh bootstrap +
  // incremental 1..2 를 격리 PostgreSQL 15 (docker postgres:15) 에서 산출: 운영 DB fingerprint 채택 아님.
  {
    appliedThrough: 'AlterHandoffTokensTargetWorkspace1789974015939',
    fingerprint: 'a9af1ccebf6278a0878ec0490036ea06b6e491ef7b1c05ee23a63129ca88e76a',
    fingerprintLineCount: 5773,
  },
  // WO-O4O-ADMIN-OPERATOR-GOOGLE-INVITATION-AND-ASSIGNMENT-CUTOVER-V1 §23 — operator_invitations
  // (token_hash UNIQUE + pending 중복 방지 partial UNIQUE + service_key/status 인덱스).
  // baseline 2026-09-18-id685 fresh bootstrap + incremental 1..3 을 격리 PostgreSQL 15
  // (docker postgres:15, 로컬 전용 포트) 에서 산출: 운영 DB fingerprint 채택 아님.
  {
    appliedThrough: 'CreateOperatorInvitations1790125106065',
    fingerprint: '3145442eb56844659a17b24354bdbf535b2088c2ae6786bff07d5917ba9bf9a6',
    fingerprintLineCount: 5798,
  },
  // WO-O4O-HOSPITAL-PHARMACY-DEVICE-ENROLLMENT-AND-LOGINLESS-ACCESS-V1 §8·§9 — hospital_devices +
  // hospital_device_enrollment_codes (해시 전용 · token_hash/code_hash UNIQUE + service_key 인덱스).
  // baseline 2026-09-18-id685 fresh bootstrap + incremental 1..4 를 격리 PostgreSQL 15
  // (docker postgres:15, 로컬 전용 포트 55433) 에서 산출: 운영 DB fingerprint 채택 아님.
  {
    appliedThrough: 'CreateHospitalDeviceTables1790125390245',
    fingerprint: 'bc27f5bc6c2077c50c0f112e863205bc14200c7284cab2c9689937a9a11e549a',
    fingerprintLineCount: 5826,
  },
  // WO-O4O-LEGACY-PASSWORD-AUTH-RETIREMENT-V1 §43 Phase B-2 (destructive · 사용자 승인 2026-09-24) —
  // service_credentials · password_reset_tokens DROP + users 의 password / reset_password_token /
  // reset_password_expires / "loginAttempts" / "lockedUntil" 컬럼 DROP.
  // **줄 수가 줄어드는 첫 항목이다**(5826 → 5793): 지금까지 incremental 은 객체를 더했고
  // 이번은 없앤다. 감소 자체가 정상이며, 그 폭이 기대와 다르면 대상이 달라졌다는 신호다.
  // baseline 2026-09-18-id685 fresh bootstrap + incremental 1..5 를 격리 PostgreSQL 15.19
  // (docker postgres:15, 로컬 전용 포트 55433, throwaway DB) 에서 산출: 운영 DB fingerprint 채택 아님.
  {
    appliedThrough: 'DropLegacyPasswordAuthSchema1790251584623',
    fingerprint: '6503cfb6ac967ed294f7cd50a56df704fced80777cab75d0dff64b2af602c72c',
    fingerprintLineCount: 5793,
  },
] as const;

/** Expected state after `prefixLength` incremental migrations; undefined when not registered. */
export function expectedSchemaStateFor(
  prefixLength: number,
  states: readonly ExpectedSchemaState[] = EXPECTED_SCHEMA_STATES,
): ExpectedSchemaState | undefined {
  if (!Number.isInteger(prefixLength) || prefixLength < 0) return undefined;
  return states[prefixLength];
}

/** Human label for a state (log lines). */
export function expectedSchemaStateLabel(state: ExpectedSchemaState | undefined): string {
  if (!state) return 'UNREGISTERED';
  return state.appliedThrough ?? `baseline ${CANONICAL_SCHEMA_BASELINE_META.baselineVersion}`;
}
