/**
 * CosmeticsCampaign Entity
 *
 * Represents a cosmetics marketing campaign
 * Auto-generated or manually created based on brand/category/concerns
 */

import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

export type CampaignType = 'brand' | 'category' | 'concern' | 'seasonal' | 'custom';

@Entity('cosmetics_campaigns')
export class CosmeticsCampaign {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  title!: string;

  @Column()
  type!: CampaignType;

  @Column({ nullable: true })
  brandId!: string;

  @Column({ nullable: true })
  category!: string;

  @Column({ type: 'jsonb', default: [] })
  concerns!: string[];

  @Column({ type: 'jsonb', default: [] })
  products!: Array<{
    productId: string;
    order?: number;
    featured?: boolean;
  }>;

  @Column({ type: 'jsonb', default: [] })
  routines!: Array<{
    routineId: string;
    order?: number;
  }>;

  @Column({ nullable: true })
  signagePlaylistId!: string;

  @Column({ type: 'jsonb', default: {} })
  metadata!: {
    autoGenerated?: boolean;
    colorTheme?: string;
    tags?: string[];
    period?: {
      startDate?: string;
      endDate?: string;
    };
    description?: string;
    bannerUrl?: string;
    status?: 'draft' | 'active' | 'expired';
  };

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
