/**
 * CosmeticsSignagePlaylist Entity
 *
 * Represents a signage playlist for digital displays
 * Contains a sequence of product, brand, routine, and category cards
 */

import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

export interface PlaylistItem {
  type: 'product' | 'brand' | 'routine' | 'category';
  productId?: string;
  brandId?: string;
  routineId?: string;
  category?: string;
  duration: number; // seconds
}

@Entity('cosmetics_signage_playlists')
export class CosmeticsSignagePlaylist {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  name!: string;

  @Column({ nullable: true })
  description!: string;

  @Column({ type: 'jsonb', default: [] })
  items!: PlaylistItem[];

  @Column({ type: 'jsonb', default: {} })
  metadata!: {
    autoGenerated?: boolean;
    filters?: {
      brand?: string;
      category?: string;
      concerns?: string[];
      skinTypes?: string[];
    };
    totalDuration?: number;
  };

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
