# O4O Platform - Web Service Cloud Build
# monorepo 루트에서 빌드, Cloud Run 배포
#
# Usage:
#   gcloud builds submit --config=cloudbuild-web.yaml \
#     --substitutions=_SERVICE_PATH=services/web-glycopharm,_IMAGE_NAME=glycopharm-web
#   gcloud builds submit --config=cloudbuild-web.yaml \
#     --substitutions=_SERVICE_PATH=apps/glucoseview-web,_IMAGE_NAME=glucoseview-web

substitutions:
  _SERVICE_PATH: services/web-glycopharm
  _IMAGE_NAME: glycopharm-web
  _REGION: asia-northeast3
  _VITE_API_BASE_URL: https://o4o-core-api-117791934476.asia-northeast3.run.app

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.web'
      - '--build-arg'
      - 'SERVICE_PATH=${_SERVICE_PATH}'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
      - '.'

  # Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_IMAGE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

timeout: '1200s'
