## API Server Deployment Script
#\!/bin/bash
# Deployment script for API Server (43.202.242.215)

echo "🚀 Starting API Server deployment..."
echo "Target: 43.202.242.215"
echo ""
echo "Please run these commands on the API server:"
echo "========================================"
echo "ssh ubuntu@43.202.242.215"
echo ""
echo "# 1. Pull latest code"
echo "cd /home/ubuntu/o4o-platform"
echo "git pull origin main"
echo ""
echo "# 2. Install dependencies (if needed)"
echo "npm install"
echo ""
echo "# 3. Build API server"
echo "npm run build:api"
echo ""
echo "# 4. Restart API server"
echo "pm2 restart api-server"
echo ""
echo "# 5. Check logs"
echo "pm2 logs api-server --lines 50"
echo ""
echo "# 6. Test SSO endpoint"
echo "curl -s 'https://api.neture.co.kr/api/v1/auth/sso/check' | python3 -m json.tool"
echo "========================================"
