packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/@o4o-apps/*'
  - 'services/*'
  - '!apps/*.backup'
  - '!packages/*.backup'
  - '!legacy/**'
  - '!legacy/*'
  - '!legacy/apps/*'
  - '!legacy/packages/*'