/**
 * 공급자 상품(Offer) 도메인 에러 코드
 *
 * Phase 2A: enum 정의만. 기존 코드의 매직 스트링은 점진적으로 교체.
 * 새로 작성하는 에러에서 우선 사용.
 */
export enum OfferErrorCode {
  // --- 조회/존재 ---
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',

  // --- 상태 ---
  INVALID_APPROVAL_STATUS = 'INVALID_APPROVAL_STATUS',
  SUPPLIER_NOT_ACTIVE = 'SUPPLIER_NOT_ACTIVE',

  // --- 검증 ---
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  INVALID_REGULATORY_TYPE = 'INVALID_REGULATORY_TYPE',
  REGULATED_FIELDS_REQUIRED = 'REGULATED_FIELDS_REQUIRED',
  INVALID_OFFER_IDS = 'INVALID_OFFER_IDS',
  INVALID_OPERATION = 'INVALID_OPERATION',
  INVALID_VALUE = 'INVALID_VALUE',

  // --- 규제/허가 ---
  PERMIT_REQUIRED_FOR_APPROVAL = 'PERMIT_REQUIRED_FOR_APPROVAL',
  PERMIT_REQUIRED_FOR_UNVERIFIED_REGULATED = 'PERMIT_REQUIRED_FOR_UNVERIFIED_REGULATED',
  // WO-O4O-REGULATED-PRODUCT-GATE-CONSOLIDATION-V1: 규제 상품은 약국 전용 서비스에만 연결 가능
  REGULATED_PRODUCT_NON_PHARMACY_SERVICE = 'REGULATED_PRODUCT_NON_PHARMACY_SERVICE',

  // --- 유통 ---
  SERVICE_REQUIRES_KEYS = 'SERVICE_REQUIRES_KEYS',
  PUBLIC_REQUIRES_DESCRIPTION = 'PUBLIC_REQUIRES_DESCRIPTION',
  PRIVATE_REQUIRES_SELLER_IDS = 'PRIVATE_REQUIRES_SELLER_IDS',

  // --- 삭제 (WO-O4O-NETURE-SUPPLIER-DELETE-POLICY-AND-REVIEW-ROUNDTRIP-BATCH-V1) ---
  /** 매장에 활성 진열이 남아 있어 삭제할 수 없다 (운영자 hard-delete 가드와 동일 조건) */
  HAS_ACTIVE_LISTINGS = 'HAS_ACTIVE_LISTINGS',
  /** 서비스 상품으로 연결돼 있어 삭제할 수 없다 */
  HAS_SERVICE_PRODUCTS = 'HAS_SERVICE_PRODUCTS',

  // (은퇴) MASTER_ID_DIRECT_INJECTION_NOT_ALLOWED — 레거시 POST /supplier/products 전용 보안 코드.
  //   WO-O4O-SUPPLIER-PRODUCT-REGISTRATION-AI-FIRST-CUTOVER-AND-LEGACY-MASTER-RESOLUTION-RETIREMENT-V1 로
  //   레거시 경로와 함께 제거. masterId 는 이제 /products/from-master 의 정식 입력이다.

  // --- 기존 Master 직접 연결 (WO-O4O-SUPPLIER-EXISTING-MASTER-DIRECT-OFFER-LINK-V1) ---
  /** masterId 가 UUID 형식이 아님 → 400 */
  INVALID_MASTER_ID = 'INVALID_MASTER_ID',
  /** product_masters 에 없음 → 404 */
  MASTER_NOT_FOUND = 'MASTER_NOT_FOUND',
  /** status ≠ ACTIVE(SUSPENDED/ARCHIVED) → 409 */
  MASTER_NOT_ACTIVE = 'MASTER_NOT_ACTIVE',
  /** regulatory_type 을 O4O canonical 로 해석할 수 없음 → 409 */
  MASTER_REGULATORY_TYPE_UNSUPPORTED = 'MASTER_REGULATORY_TYPE_UNSUPPORTED',
  /** body 에 Master 기준정보 필드(barcode/name/regulatoryType …)가 포함됨 → 400 */
  MASTER_FIELD_NOT_ALLOWED = 'MASTER_FIELD_NOT_ALLOWED',
  /** body 에 supplierId 가 포함됨(middleware 확정값만 사용) → 400 */
  SUPPLIER_ID_NOT_ALLOWED = 'SUPPLIER_ID_NOT_ALLOWED',
  /** 허용 목록 밖의 body 키 → 400 */
  UNSUPPORTED_FIELD = 'UNSUPPORTED_FIELD',

  // --- 시스템 ---
  MASTER_RESOLVE_FAILED = 'MASTER_RESOLVE_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
