/**
 * 공급자 상품(Offer) 도메인 에러 코드
 *
 * Phase 2A: enum 정의만. 기존 코드의 매직 스트링은 점진적으로 교체.
 * 새로 작성하는 에러에서 우선 사용.
 */
export enum OfferErrorCode {
  // --- 조회/존재 ---
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',

  // --- 상태 ---
  INVALID_APPROVAL_STATUS = 'INVALID_APPROVAL_STATUS',
  SUPPLIER_NOT_ACTIVE = 'SUPPLIER_NOT_ACTIVE',

  // --- 검증 ---
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  INVALID_REGULATORY_TYPE = 'INVALID_REGULATORY_TYPE',
  REGULATED_FIELDS_REQUIRED = 'REGULATED_FIELDS_REQUIRED',
  INVALID_OFFER_IDS = 'INVALID_OFFER_IDS',
  INVALID_OPERATION = 'INVALID_OPERATION',
  INVALID_VALUE = 'INVALID_VALUE',

  // --- 규제/허가 ---
  PERMIT_REQUIRED_FOR_APPROVAL = 'PERMIT_REQUIRED_FOR_APPROVAL',
  PERMIT_REQUIRED_FOR_UNVERIFIED_REGULATED = 'PERMIT_REQUIRED_FOR_UNVERIFIED_REGULATED',
  // WO-O4O-REGULATED-PRODUCT-GATE-CONSOLIDATION-V1: 규제 상품은 약국 전용 서비스에만 연결 가능
  REGULATED_PRODUCT_NON_PHARMACY_SERVICE = 'REGULATED_PRODUCT_NON_PHARMACY_SERVICE',

  // --- 유통 ---
  SERVICE_REQUIRES_KEYS = 'SERVICE_REQUIRES_KEYS',
  PUBLIC_REQUIRES_DESCRIPTION = 'PUBLIC_REQUIRES_DESCRIPTION',
  PRIVATE_REQUIRES_SELLER_IDS = 'PRIVATE_REQUIRES_SELLER_IDS',

  // --- 보안 ---
  MASTER_ID_DIRECT_INJECTION_NOT_ALLOWED = 'MASTER_ID_DIRECT_INJECTION_NOT_ALLOWED',

  // --- 시스템 ---
  MASTER_RESOLVE_FAILED = 'MASTER_RESOLVE_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
