/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_USE_MOCK: string
  readonly VITE_OAUTH_REDIRECT_URI: string
  readonly VITE_OAUTH_GOOGLE_CLIENT_ID: string
  readonly VITE_OAUTH_KAKAO_CLIENT_ID: string
  readonly VITE_OAUTH_NAVER_CLIENT_ID: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

declare module '@wordpress/icons' {
  export const Icon: any
  export const chevronLeft: any
  export const chevronRight: any
  export const check: any
  export const chevronDown: any
  export const close: any
  export const edit: any
  export const plus: any
  export const trash: any
}

declare module 'lucide-react' {
  export const Search: any
  export const Menu: any
  export const X: any
  export const Home: any
  export const Package: any
  export const ShoppingCart: any
  export const Users: any
  export const Settings: any
  export const LogOut: any
  export const Sun: any
  export const Moon: any
  export const ChevronDown: any
  export const Calendar: any
  export const ArrowUpDown: any
  export const Edit: any
  export const Trash2: any
  export const Eye: any
  export const Plus: any
  export const Filter: any
  export const Save: any
  export const Check: any
  export const FileText: any
  export const ChevronLeft: any
  export const ChevronRight: any
  export const Upload: any
  export const Download: any
  export const RefreshCw: any
  export const Bell: any
  export const User: any
  export const UserCheck: any
  export const UserX: any
  export const Ban: any
  export const Shield: any
  export const AlertCircle: any
  export const Loader: any
  export const Loader2: any
  export const Copy: any
  export const ExternalLink: any
  export const MoreVertical: any
  export const MoreHorizontal: any
  export const CreditCard: any
  export const DollarSign: any
  export const TrendingUp: any
  export const TrendingDown: any
  export const Activity: any
  export const AlertTriangle: any
  export const CheckCircle: any
  export const Info: any
  export const HelpCircle: any
  export const Clock: any
  export const Zap: any
  export const Database: any
  export const Server: any
  export const Cpu: any
  export const HardDrive: any
  export const BarChart: any
  export const LineChart: any
  export const PieChart: any
  export const Mail: any
  export const MessageSquare: any
  export const Send: any
  export const Inbox: any
  export const Archive: any
  export const Trash: any
  export const Star: any
  export const Flag: any
  export const Tag: any
  export const Tags: any
  export const Hash: any
  export const Bookmark: any
  export const Heart: any
  export const Share: any
  export const Share2: any
  export const Link: any
  export const Code: any
  export const Terminal: any
  export const Command: any
  export const Cloud: any
  export const Wifi: any
  export const WifiOff: any
  export const Building: any
  export const Store: any
  export const ShoppingBag: any
  export const Package2: any
  export const Truck: any
  export const MapPin: any
  export const Phone: any
  export const Camera: any
  export const Image: any
  export const Film: any
  export const Mic: any
  export const Volume: any
  export const Volume2: any
  export const VolumeX: any
  export const Play: any
  export const Pause: any
  export const SkipForward: any
  export const SkipBack: any
  export const FastForward: any
  export const Rewind: any
  export const RefreshCcw: any
  export const Repeat: any
  export const List: any
  export const Grid: any
  export const Layers: any
  export const Layout: any
  export const Palette: any
  export const Brush: any
  export const PenTool: any
  export const Crop: any
  export const Scissors: any
  export const Move: any
  export const Maximize: any
  export const Minimize: any
  export const Expand: any
  export const Shrink: any
  export const Lock: any
  export const Unlock: any
  export const Key: any
  export const UserPlus: any
  export const UserMinus: any
  export const Award: any
  export const Gift: any
  export const Trophy: any
  export const Crown: any
  export const Medal: any
  export const Target: any
  export const Crosshair: any
  export const Compass: any
  export const Map: any
  export const Navigation: any
  export const Globe: any
  export const Sunrise: any
  export const Sunset: any
  export const CloudRain: any
  export const CloudSnow: any
  export const Wind: any
  export const Thermometer: any
  export const Battery: any
  export const BatteryCharging: any
  export const Bluetooth: any
  export const Printer: any
  export const Monitor: any
  export const Smartphone: any
  export const Tablet: any
  export const Laptop: any
  export const Watch: any
  export const Headphones: any
  export const Speaker: any
  export const Tv: any
  export const Radio: any
  export const Cast: any
  export const Airplay: any
  export const Chrome: any
  export const Facebook: any
  export const Instagram: any
  export const Twitter: any
  export const Youtube: any
  export const Linkedin: any
  export const Github: any
  export const Gitlab: any
  export const Slack: any
  export const Twitch: any
  export const Briefcase: any
  export const Folder: any
  export const FolderOpen: any
  export const FolderPlus: any
  export const FolderMinus: any
  export const File: any
  export const FilePlus: any
  export const FileMinus: any
  export const FileCheck: any
  export const FileX: any
  export const Paperclip: any
  export const Clipboard: any
  export const ClipboardCheck: any
  export const ClipboardX: any
  export const XCircle: any
  export const CheckSquare: any
  export const Square: any
  export const Circle: any
  export const Disc: any
  export const Minus: any
  export const MinusCircle: any
  export const MinusSquare: any
  export const PlusCircle: any
  export const PlusSquare: any
  export const UploadCloud: any
  export const DownloadCloud: any
  export const Percent: any
}