/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_API_BASE_URL: string  // Add for compatibility
  readonly VITE_AUTH_URL: string
  readonly VITE_OAUTH_REDIRECT_URI: string
  readonly VITE_OAUTH_GOOGLE_CLIENT_ID: string
  readonly VITE_OAUTH_KAKAO_CLIENT_ID: string
  readonly VITE_OAUTH_NAVER_CLIENT_ID: string
  readonly VITE_FORUM_URL: string
  readonly VITE_SIGNAGE_URL: string
  readonly VITE_FUNDING_URL: string
  readonly VITE_SSO_ENABLED: string
  readonly VITE_SSO_DOMAIN: string
  readonly VITE_USE_MOCK: string
  readonly DEV: boolean  // Add Vite's dev mode flag
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

// WordPress type declarations
declare module '@wordpress/blocks' {
  export function registerBlockType(name: string, settings: any): any
  export function createBlock(name: string, attributes?: any): any
  export function serialize(blocks: any): string
  export function parse(content: string): any[]
  export const store: any
}

declare module '@wordpress/block-editor' {
  export const InspectorControls: any
  export const BlockControls: any
  export const MediaUpload: any
  export const MediaUploadCheck: any
  export const InnerBlocks: any
  export const useBlockProps: any
  export const RichText: any
  export const PanelColorSettings: any
  export const URLInput: any
  export const AlignmentToolbar: any
  export const BlockAlignmentToolbar: any
  export const BlockVerticalAlignmentToolbar: any
  export const ColorPalette: any
  export const store: any
  export const BlockEditorProvider: any
  export const BlockList: any
  export const WritingFlow: any
  export const ObserveTyping: any
  export const BlockInspector: any
  export const BlockToolbar: any
}

declare module '@wordpress/data' {
  export function useSelect(callback: (select: any) => any, deps?: any[]): any
  export function useDispatch(storeName: string): any
  export function select(storeName: string): any
  export function dispatch(storeName: string): any
  export function subscribe(callback: () => void): () => void
  export function createRegistry(): any
  export function createRegistrySelector(selector: any): any
  export function createRegistryControl(control: any): any
}

declare module '@wordpress/icons' {
  export const Icon: any
  export const chevronLeft: any
  export const chevronRight: any
  export const check: any
  export const chevronDown: any
  export const close: any
  export const edit: any
  export const plus: any
  export const trash: any
  export const settings: any
  export const dragHandle: any
  export const seen: any
  export const unseen: any
  export const cog: any
  export const calendar: any
  export const starEmpty: any
  export const starHalf: any
  export const filter: any
  export const grid: any
  export const listView: any
  export const update: any
  export const list: any
  export const loop: any
}

declare module '@wordpress/url' {
  export function addQueryArgs(url: string, args: Record<string, any>): string
  export function removeQueryArgs(url: string, ...args: string[]): string
  export function getQueryArg(url: string, arg: string): string | undefined
  export function getQueryArgs(url: string): Record<string, string>
  export function buildQueryString(args: Record<string, any>): string
  export function getPath(url: string): string
  export function getFragment(url: string): string
  export function isValidProtocol(protocol: string): boolean
  export function isValidAuthority(authority: string): boolean
  export function isValidPath(path: string): boolean
  export function isValidQueryString(queryString: string): boolean
  export function isValidFragment(fragment: string): boolean
  export function isURL(url: string): boolean
  export function getProtocol(url: string): string | undefined
  export function getAuthority(url: string): string | undefined
  export function filterURLForDisplay(url: string, maxLength?: number): string
  export function safeDecodeURI(uri: string): string
  export function safeDecodeURIComponent(uriComponent: string): string
}

declare module '@heroicons/react/24/outline' {
  export const ChevronDownIcon: any
  export const ChevronRightIcon: any
  export const HomeIcon: any
  export const UsersIcon: any
  export const ChartBarIcon: any
  export const CogIcon: any
  export const ShoppingCartIcon: any
  export const GlobeAltIcon: any
  export const CubeIcon: any
  export const DocumentDuplicateIcon: any
  export const PuzzlePieceIcon: any
  export const BeakerIcon: any
  export const StarIcon: any
  export const ShieldCheckIcon: any
  export const BanknotesIcon: any
  export const ClipboardDocumentListIcon: any
  export const WrenchIcon: any
  export const AdjustmentsHorizontalIcon: any
  export const Squares2X2Icon: any
  export const SwatchIcon: any
  export const CodeBracketIcon: any
  export const DocumentTextIcon: any
  export const PhotoIcon: any
  export const CircleStackIcon: any
  export const PaintBrushIcon: any
}

// Testing library type declarations
declare module 'msw' {
  export const http: {
    get: (path: string, handler: any) => any
    post: (path: string, handler: any) => any
    put: (path: string, handler: any) => any
    patch: (path: string, handler: any) => any
    delete: (path: string, handler: any) => any
  }
  export class HttpResponse {
    static json(body: any, options?: any): any
    static text(body: string, options?: any): any
  }
  export function delay(ms?: number): Promise<void>
}

declare module 'vitest' {
  export const vi: {
    fn: (implementation?: any) => any
    spyOn: (obj: any, method: string) => any
    mock: (path: string, factory?: () => any) => any
    clearAllMocks: () => void
    resetAllMocks: () => void
    restoreAllMocks: () => void
    importActual: (path: string) => Promise<any>
  }
  export const expect: any
  export const test: any
  export const describe: any
  export const it: any
  export const beforeEach: any
  export const afterEach: any
  export const beforeAll: any
  export const afterAll: any
}

declare module 'lodash' {
  export function debounce(func: any, wait?: number): any
  export function throttle(func: any, wait?: number): any
  export function cloneDeep(value: any): any
  export function merge(...args: any[]): any
  export function get(object: any, path: string, defaultValue?: any): any
  export function set(object: any, path: string, value: any): any
  export function has(object: any, path: string): boolean
  export function isEmpty(value: any): boolean
  export function isEqual(value: any, other: any): boolean
  export function omit(object: any, ...paths: string[]): any
  export function pick(object: any, ...paths: string[]): any
}

// NodeJS namespace for SSO
declare namespace NodeJS {
  interface ProcessEnv {
    NODE_ENV: 'development' | 'production' | 'test'
    [key: string]: string | undefined
  }
  type Timeout = ReturnType<typeof setTimeout>
  type Timer = ReturnType<typeof setInterval>
}

// Global process object
declare const process: {
  env: NodeJS.ProcessEnv
}

// Testing library declarations
declare module 'msw/browser' {
  export function setupWorker(...handlers: any[]): any
}

declare module 'msw/node' {
  export function setupServer(...handlers: any[]): any
}

declare module '@testing-library/react' {
  export function render(component: any, options?: any): any
  export function waitFor(callback: () => any, options?: any): Promise<any>
  export function screen(): any
  export const fireEvent: any
  export const act: any
}

declare module '@testing-library/jest-dom' {
  const content: any
  export default content
}

declare module 'react-dom/client' {
  export function createRoot(container: Element | DocumentFragment): {
    render(element: React.ReactNode): void
    unmount(): void
  }
  export function hydrateRoot(container: Element | Document, initialChildren: React.ReactNode): {
    render(element: React.ReactNode): void
    unmount(): void
  }
}

declare module 'react-dom' {
  export * from 'react-dom'
}

declare module 'lucide-react' {
  export const Search: any
  export const Menu: any
  export const X: any
  export const Home: any
  export const Package: any
  export const ShoppingCart: any
  export const Users: any
  export const Settings: any
  export const LogOut: any
  export const Sun: any
  export const Moon: any
  export const ChevronDown: any
  export const Calendar: any
  export const ArrowUpDown: any
  export const Edit: any
  export const Trash2: any
  export const Eye: any
  export const Plus: any
  export const Filter: any
  export const Save: any
  export const Check: any
  export const FileText: any
  export const ChevronLeft: any
  export const ChevronRight: any
  export const Upload: any
  export const Download: any
  export const RefreshCw: any
  export const Bell: any
  export const User: any
  export const UserCheck: any
  export const UserX: any
  export const Ban: any
  export const Shield: any
  export const AlertCircle: any
  export const Loader: any
  export const Loader2: any
  export const Copy: any
  export const ExternalLink: any
  export const MoreVertical: any
  export const MoreHorizontal: any
  export const CreditCard: any
  export const DollarSign: any
  export const TrendingUp: any
  export const TrendingDown: any
  export const Activity: any
  export const AlertTriangle: any
  export const CheckCircle: any
  export const Info: any
  export const HelpCircle: any
  export const Clock: any
  export const Zap: any
  export const Database: any
  export const Server: any
  export const Cpu: any
  export const HardDrive: any
  export const BarChart: any
  export const LineChart: any
  export const PieChart: any
  export const Mail: any
  export const MessageSquare: any
  export const Send: any
  export const Inbox: any
  export const Archive: any
  export const Trash: any
  export const Star: any
  export const Flag: any
  export const Tag: any
  export const Tags: any
  export const Hash: any
  export const Bookmark: any
  export const Heart: any
  export const Share: any
  export const Share2: any
  export const Link: any
  export const Code: any
  export const Terminal: any
  export const Command: any
  export const Cloud: any
  export const Wifi: any
  export const WifiOff: any
  export const Building: any
  export const Store: any
  export const ShoppingBag: any
  export const Package2: any
  export const Truck: any
  export const MapPin: any
  export const Phone: any
  export const Camera: any
  export const Image: any
  export const Film: any
  export const Mic: any
  export const Volume: any
  export const Volume2: any
  export const VolumeX: any
  export const Play: any
  export const Pause: any
  export const SkipForward: any
  export const SkipBack: any
  export const FastForward: any
  export const Rewind: any
  export const RefreshCcw: any
  export const Repeat: any
  export const List: any
  export const Grid: any
  export const Layers: any
  export const Layout: any
  export const Palette: any
  export const Brush: any
  export const PenTool: any
  export const Crop: any
  export const Scissors: any
  export const Move: any
  export const Maximize: any
  export const Minimize: any
  export const Expand: any
  export const Shrink: any
  export const Lock: any
  export const Unlock: any
  export const Key: any
  export const UserPlus: any
  export const UserMinus: any
  export const Award: any
  export const Gift: any
  export const Trophy: any
  export const Crown: any
  export const Medal: any
  export const Target: any
  export const Crosshair: any
  export const Compass: any
  export const Map: any
  export const Navigation: any
  export const Globe: any
  export const Sunrise: any
  export const Sunset: any
  export const CloudRain: any
  export const CloudSnow: any
  export const Wind: any
  export const Thermometer: any
  export const Battery: any
  export const BatteryCharging: any
  export const Bluetooth: any
  export const Printer: any
  export const Monitor: any
  export const Smartphone: any
  export const Tablet: any
  export const Laptop: any
  export const Watch: any
  export const Headphones: any
  export const Speaker: any
  export const Tv: any
  export const Radio: any
  export const Cast: any
  export const Airplay: any
  export const Chrome: any
  export const Facebook: any
  export const Instagram: any
  export const Twitter: any
  export const Youtube: any
  export const Linkedin: any
  export const Github: any
  export const Gitlab: any
  export const Slack: any
  export const Twitch: any
  export const Briefcase: any
  export const Folder: any
  export const FolderOpen: any
  export const FolderPlus: any
  export const FolderMinus: any
  export const File: any
  export const FilePlus: any
  export const FileMinus: any
  export const FileCheck: any
  export const FileX: any
  export const Paperclip: any
  export const Clipboard: any
  export const ClipboardCheck: any
  export const ClipboardX: any
  export const XCircle: any
  export const CheckSquare: any
  export const Square: any
  export const Circle: any
  export const Disc: any
  export const Minus: any
  export const MinusCircle: any
  export const MinusSquare: any
  export const PlusCircle: any
  export const PlusSquare: any
  export const UploadCloud: any
  export const DownloadCloud: any
  export const Percent: any
  export const ArrowLeft: any
  export const BarChart3: any
  export const LayoutGrid: any
  export const CloudOff: any
  export const GripVertical: any
  export const ChevronUp: any
  export const Edit2: any
  export const CheckCircle2: any
  export const Type: any
  export const ToggleLeft: any
  export const Group: any
  export const Images: any
  export const GitBranch: any
  export const Link2: any
  export const QrCode: any
  export const Sparkles: any
  export const ChevronsLeft: any
  export const ChevronsRight: any
  export const ToggleRight: any
  export const Hash2: any
  export const PersonStanding: any
  export const Gauge: any
  export const PackageSearch: any
  export const Construction: any
  export const Blocks: any
  export const Rows: any
  export const Columns3: any
  export const GripHorizontal: any
  export const PanelLeft: any
  export const ClipboardList: any
  export const ListTree: any
  export const ArrowUpFromLine: any
  export const Import: any
  export const Export: any
  export const NotepadText: any
  export const CalendarDays: any
  export const MapPinned: any
  export const CircleDollarSign: any
  export const Banknote: any
  export const CreditCardIcon: any
  export const MousePointer2: any
  export const Coins: any
  export const CircleCheckBig: any
  export const PackageCheck: any
  export const FolderTree: any
  export const ShoppingBag2: any
  export const Binary: any
  export const Webhook: any
  export const Workflow: any
  export const GitPullRequest: any
  export const TestTube: any
  export const Lightbulb: any
  export const Box: any
  export const PackageOpen: any
  export const Scale: any
  export const Calculator: any
  export const Boxes: any
  export const Files: any
  export const ShieldCheck: any
  export const ShieldX: any
  export const ShieldAlert: any
  export const BarChart2: any
  export const PieChart2: any
  export const LineChart2: any
  export const WalletCards: any
  export const ChevronFirst: any
  export const ChevronLast: any
  export const MessageCircleReply: any
  export const MessageCircleHeart: any
  export const MessageCircleWarning: any
  export const MessageCircleX: any
  export const LogInIcon: any
  export const LayoutDashboard: any
  export const ChevronRightCircle: any
  export const ChevronLeftCircle: any
  export const ChevronUpCircle: any
  export const ChevronDownCircle: any
  export const PackagePlus: any
  export const Rocket: any
  export const Megaphone: any
  export const TrendingUpDown: any
  export const UserCog: any
  export const FileBarChart: any
  export const TagIcon: any
  export const Globe2: any
  export const GlobeIcon: any
  export const PencilIcon: any
  export const Wrench: any
  export const AlignLeft: any
  export const AlignCenter: any
  export const AlignRight: any
  export const AlignJustify: any
  export const Hash3: any
  export const Hash4: any
  export const Hash5: any
  export const Hash6: any
  export const ChefHat: any
  export const Ratio: any
  export const HeartHandshake: any
  export const ReceiptText: any
  export const Languages: any
  export const Repeat2: any
  export const Network: any
  export const AlertOctagon: any
  export const PackageIcon: any
  export const XIcon: any
  export const BoxSelect: any
  export const TerminalSquare: any
  export const PaletteIcon: any
  export const Paintbrush: any
  export const Maximize2: any
  export const Minimize2: any
  export const History: any
  export const XSquare: any
  export const ShieldQuestion: any
  export const ListPlus: any
  export const ListMinus: any
  export const ListX: any
  export const ListChecks: any
  export const ListOrdered: any
  export const SquareStack: any
  export const Underline: any
  export const Strikethrough: any
  export const Subscript: any
  export const Superscript: any
  export const Pilcrow: any
  export const RemoveFormatting: any
  export const Divide: any
  export const PlusIcon: any
  export const ArrowUpCircle: any
  export const ArrowDownCircle: any
  export const ArrowLeftCircle: any
  export const ArrowRightCircle: any
  export const BrainCircuit: any
  export const BrainCog: any
  export const ServerCog: any
  export const Fingerprint: any
  export const Scan: any
  export const ScanLine: any
  export const BarcodeScan: any
  export const QrCodeIcon: any
  export const MonitorSmartphone: any
  export const MonitorSpeaker: any
  export const Laptop2: any
  export const TabletSmartphone: any
  export const BookOpen: any
  export const Grid3X3: any
  export const Columns: any
  export const Quote: any
  export const Table: any
  export const Video: any
  export const Music: any
  export const RectangleHorizontal: any
  export const Bold: any
  export const Italic: any
  export const Undo: any
  export const Redo: any
  export const Heading1: any
  export const Heading2: any
  export const Heading3: any
  export const ArrowRight: any
  export const Ellipsis: any
  export const SquareCheck: any
  export const SquareCheckBig: any
  export const Library: any
  export const MousePointerClick: any
  export const ScrollText: any
  export const TextSelect: any
  export const TextCursor: any
  export const TextCursorInput: any
  export const Highlighter: any
  export const PenLine: any
  export const NotebookPen: any
  export const NotebookTabs: any
  export const BookMarked: any
  export const BookOpenCheck: any
  export const BookOpenText: any
  export const BookText: any
  export const BookType: any
  export const BookUser: any
  export const BookCheck: any
  export const BookCopy: any
  export const BookDashed: any
  export const BookHeadphones: any
  export const BookHeart: any
  export const BookImage: any
  export const BookKey: any
  export const BookLock: any
  export const BookMinus: any
  export const BookPlus: any
  export const BookUp: any
  export const BookUp2: any
  export const BookX: any
  export const BookAudio: any
  export const BookmarkCheck: any
  export const BookmarkMinus: any
  export const BookmarkPlus: any
  export const BookmarkX: any
  export const Bookmarks: any
  export const BoomBox: any
  export const Bot: any
  export const BotMessageSquare: any
  export const BrainCircuit: any
  export const BrainCog: any
  export const Briefcase: any
  export const BriefcaseBusiness: any
  export const BriefcaseMedical: any
  export const BringToFront: any
  export const Brush: any
  export const Bug: any
  export const BugOff: any
  export const BugPlay: any
  export const Building: any
  export const Building2: any
  export const Bus: any
  export const BusFront: any
  export const Cable: any
  export const CableCar: any
  export const Cake: any
  export const CakeSlice: any
  export const Calculator: any
  export const Calendar: any
  export const CalendarArrowDown: any
  export const CalendarArrowUp: any
  export const CalendarCheck: any
  export const CalendarCheck2: any
  export const CalendarClock: any
  export const CalendarCog: any
  export const CalendarDays: any
  export const CalendarFold: any
  export const CalendarHeart: any
  export const CalendarMinus: any
  export const CalendarMinus2: any
  export const CalendarOff: any
  export const CalendarPlus: any
  export const CalendarPlus2: any
  export const CalendarRange: any
  export const CalendarSearch: any
  export const CalendarX: any
  export const CalendarX2: any
  export const Camera: any
  export const CameraOff: any
  export const CandlestickChart: any
  export const Candy: any
  export const CandyCane: any
  export const CandyOff: any
  export const Cannabis: any
  export const Captions: any
  export const CaptionsOff: any
  export const Car: any
  export const CarFront: any
  export const CarTaxiFront: any
  export const Caravan: any
  export const Carrot: any
  export const CaseLower: any
  export const CaseSensitive: any
  export const CaseUpper: any
  export const CassetteTape: any
  export const Cast: any
  export const Castle: any
  export const Cat: any
  export const Cctv: any
  export const ChartArea: any
  export const ChartBar: any
  export const ChartBarBig: any
  export const ChartBarDecreasing: any
  export const ChartBarIncreasing: any
  export const ChartBarStacked: any
  export const ChartCandlestick: any
  export const ChartColumn: any
  export const ChartColumnBig: any
  export const ChartColumnDecreasing: any
  export const ChartColumnIncreasing: any
  export const ChartColumnStacked: any
  export const ChartGantt: any
  export const ChartLine: any
  export const ChartNetwork: any
  export const ChartNoAxesColumn: any
  export const ChartNoAxesColumnDecreasing: any
  export const ChartNoAxesColumnIncreasing: any
  export const ChartNoAxesCombined: any
  export const ChartNoAxesGantt: any
  export const ChartPie: any
  export const ChartScatter: any
  export const ChartSpline: any
  export const Check: any
  export const CheckCheck: any
  export const CheckCircle: any
  export const CheckCircle2: any
  export const CheckSquare: any
  export const CheckSquare2: any
  export const ChefHat: any
  export const Cherry: any
  export const ChevronDown: any
  export const ChevronDownCircle: any
  export const ChevronDownSquare: any
  export const ChevronFirst: any
  export const ChevronLast: any
  export const ChevronLeft: any
  export const ChevronLeftCircle: any
  export const ChevronLeftSquare: any
  export const ChevronRight: any
  export const ChevronRightCircle: any
  export const ChevronRightSquare: any
  export const ChevronUp: any
  export const ChevronUpCircle: any
  export const ChevronUpSquare: any
  export const ChevronsDown: any
  export const ChevronsDownUp: any
  export const ChevronsLeft: any
  export const ChevronsLeftRight: any
  export const ChevronsLeftRightEllipsis: any
  export const ChevronsRight: any
  export const ChevronsRightLeft: any
  export const ChevronsUp: any
  export const ChevronsUpDown: any
  export const Chrome: any
  export const Church: any
  export const Cigarette: any
  export const CigaretteOff: any
  export const Circle: any
  export const CircleAlert: any
  export const CircleArrowDown: any
  export const CircleArrowLeft: any
  export const CircleArrowOutDownLeft: any
  export const CircleArrowOutDownRight: any
  export const CircleArrowOutUpLeft: any
  export const CircleArrowOutUpRight: any
  export const CircleArrowRight: any
  export const CircleArrowUp: any
  export const CircleCheckBig: any
  export const CircleChevronDown: any
  export const CircleChevronLeft: any
  export const CircleChevronRight: any
  export const CircleChevronUp: any
  export const CircleDashed: any
  export const CircleDollarSign: any
  export const CircleDot: any
  export const CircleDotDashed: any
  export const CircleEllipsis: any
  export const CircleEqual: any
  export const CircleFadingArrowUp: any
  export const CircleFadingPlus: any
  export const CircleGauge: any
  export const CircleHelp: any
  export const CircleMinus: any
  export const CircleOff: any
  export const CircleParking: any
  export const CircleParkingOff: any
  export const CirclePause: any
  export const CirclePercent: any
  export const CirclePlay: any
  export const CirclePlus: any
  export const CirclePower: any
  export const CircleSlash: any
  export const CircleSlash2: any
  export const CircleStop: any
  export const CircleUser: any
  export const CircleUserRound: any
  export const CircleX: any
  export const CircuitBoard: any
  export const Citrus: any
  export const Clapperboard: any
  export const Clipboard: any
  export const ClipboardCheck: any
  export const ClipboardCopy: any
  export const ClipboardList: any
  export const ClipboardMinus: any
  export const ClipboardPaste: any
  export const ClipboardPen: any
  export const ClipboardPenLine: any
  export const ClipboardPlus: any
  export const ClipboardType: any
  export const ClipboardX: any
  export const Clock: any
  export const Clock1: any
  export const Clock10: any
  export const Clock11: any
  export const Clock12: any
  export const Clock2: any
  export const Clock3: any
  export const Clock4: any
  export const Clock5: any
  export const Clock6: any
  export const Clock7: any
  export const Clock8: any
  export const Clock9: any
  export const ClockAlert: any
  export const ClockArrowDown: any
  export const ClockArrowUp: any
  export const Cloud: any
  export const CloudAlert: any
  export const CloudCog: any
  export const CloudDownload: any
  export const CloudDrizzle: any
  export const CloudFog: any
  export const CloudHail: any
  export const CloudLightning: any
  export const CloudMoon: any
  export const CloudMoonRain: any
  export const CloudOff: any
  export const CloudRain: any
  export const CloudRainWind: any
  export const CloudSnow: any
  export const CloudSun: any
  export const CloudSunRain: any
  export const CloudUpload: any
  export const Cloudy: any
  export const Clover: any
  export const Club: any
  export const Code: any
  export const Code2: any
  export const CodeXml: any
  export const Codepen: any
  export const Codesandbox: any
  export const Coffee: any
  export const Cog: any
  export const Coins: any
  export const Columns2: any
  export const Columns3: any
  export const Columns4: any
  export const Combine: any
  export const Command: any
  export const Compass: any
  export const Component: any
  export const Computer: any
  export const ConciergeBell: any
  export const Cone: any
  export const Construction: any
  export const Contact: any
  export const ContactRound: any
  export const Container: any
  export const Contrast: any
  export const Cookie: any
  export const CookingPot: any
  export const Copy: any
  export const CopyCheck: any
  export const CopyMinus: any
  export const CopyPlus: any
  export const CopySlash: any
  export const CopyX: any
  export const Copyleft: any
  export const Copyright: any
  export const CornerDownLeft: any
  export const CornerDownRight: any
  export const CornerLeftDown: any
  export const CornerLeftUp: any
  export const CornerRightDown: any
  export const CornerRightUp: any
  export const CornerUpLeft: any
  export const CornerUpRight: any
  export const Cpu: any
  export const CreativeCommons: any
  export const CreditCard: any
  export const Croissant: any
  export const Crop: any
  export const Cross: any
  export const Crosshair: any
  export const Crown: any
  export const Cuboid: any
  export const CupSoda: any
  export const Currency: any
  export const Cylinder: any
  export const Dam: any
  export const Database: any
  export const DatabaseBackup: any
  export const DatabaseZap: any
  export const Delete: any
  export const Dessert: any
  export const Diameter: any
  export const Diamond: any
  export const DiamondMinus: any
  export const DiamondPercent: any
  export const DiamondPlus: any
  export const Dice1: any
  export const Dice2: any
  export const Dice3: any
  export const Dice4: any
  export const Dice5: any
  export const Dice6: any
  export const Dices: any
  export const Diff: any
  export const Disc: any
  export const Disc2: any
  export const Disc3: any
  export const DiscAlbum: any
  export const Divide: any
  export const DivideCircle: any
  export const DivideSquare: any
  export const Dna: any
  export const DnaOff: any
  export const Dock: any
  export const Dog: any
  export const DollarSign: any
  export const Donut: any
  export const DoorClosed: any
  export const DoorOpen: any
  export const Dot: any
  export const DotSquare: any
  export const Download: any
  export const DownloadCloud: any
  export const DraftingCompass: any
  export const Drama: any
  export const Dribbble: any
  export const Drill: any
  export const Droplet: any
  export const Droplets: any
  export const Drum: any
  export const Drumstick: any
  export const Dumbbell: any
  export const Ear: any
  export const EarOff: any
  export const Earth: any
  export const EarthLock: any
  export const Eclipse: any
  export const Edit: any
  export const Edit2: any
  export const Edit3: any
  export const Egg: any
  export const EggFried: any
  export const EggOff: any
  export const Ellipsis: any
  export const EllipsisVertical: any
  export const Equal: any
  export const EqualNot: any
  export const EqualSquare: any
  export const Eraser: any
  export const EthernetPort: any
  export const Euro: any
  export const Expand: any
  export const ExternalLink: any
  export const Eye: any
  export const EyeClosed: any
  export const EyeOff: any
  export const Facebook: any
  export const Factory: any
  export const Fan: any
  export const FastForward: any
  export const Feather: any
  export const Fence: any
  export const FerrisWheel: any
  export const Figma: any
  export const File: any
  export const FileArchive: any
  export const FileAudio: any
  export const FileAudio2: any
  export const FileAxis3d: any
  export const FileBadge: any
  export const FileBadge2: any
  export const FileBarChart: any
  export const FileBarChart2: any
  export const FileBox: any
  export const FileChartColumn: any
  export const FileChartColumnIncreasing: any
  export const FileChartLine: any
  export const FileChartPie: any
  export const FileCheck: any
  export const FileCheck2: any
  export const FileClock: any
  export const FileCode: any
  export const FileCode2: any
  export const FileCog: any
  export const FileDiff: any
  export const FileDigit: any
  export const FileDown: any
  export const FileHeart: any
  export const FileImage: any
  export const FileInput: any
  export const FileJson: any
  export const FileJson2: any
  export const FileKey: any
  export const FileKey2: any
  export const FileLineChart: any
  export const FileLock: any
  export const FileLock2: any
  export const FileMinus: any
  export const FileMinus2: any
  export const FileMusic: any
  export const FileOutput: any
  export const FilePen: any
  export const FilePenLine: any
  export const FilePieChart: any
  export const FilePlus: any
  export const FilePlus2: any
  export const FileQuestion: any
  export const FileScan: any
  export const FileSearch: any
  export const FileSearch2: any
  export const FileSliders: any
  export const FileSpreadsheet: any
  export const FileStack: any
  export const FileSymlink: any
  export const FileTerminal: any
  export const FileText: any
  export const FileType: any
  export const FileType2: any
  export const FileUp: any
  export const FileUser: any
  export const FileVideo: any
  export const FileVideo2: any
  export const FileVolume: any
  export const FileVolume2: any
  export const FileWarning: any
  export const FileX: any
  export const FileX2: any
  export const Files: any
  export const Film: any
  export const Filter: any
  export const FilterX: any
  export const Fingerprint: any
  export const FireExtinguisher: any
  export const Fish: any
  export const FishOff: any
  export const FishSymbol: any
  export const Flag: any
  export const FlagOff: any
  export const FlagTriangleLeft: any
  export const FlagTriangleRight: any
  export const Flame: any
  export const FlameKindling: any
  export const Flashlight: any
  export const FlashlightOff: any
  export const FlaskConical: any
  export const FlaskConicalOff: any
  export const FlaskRound: any
  export const FlipHorizontal: any
  export const FlipHorizontal2: any
  export const FlipVertical: any
  export const FlipVertical2: any
  export const Flower: any
  export const Flower2: any
  export const Focus: any
  export const FoldHorizontal: any
  export const FoldVertical: any
  export const Folder: any
  export const FolderArchive: any
  export const FolderCheck: any
  export const FolderClock: any
  export const FolderClosed: any
  export const FolderCog: any
  export const FolderDot: any
  export const FolderDown: any
  export const FolderGit: any
  export const FolderGit2: any
  export const FolderHeart: any
  export const FolderInput: any
  export const FolderKanban: any
  export const FolderKey: any
  export const FolderLock: any
  export const FolderMinus: any
  export const FolderOpen: any
  export const FolderOpenDot: any
  export const FolderOutput: any
  export const FolderPen: any
  export const FolderPlus: any
  export const FolderRoot: any
  export const FolderSearch: any
  export const FolderSearch2: any
  export const FolderSymlink: any
  export const FolderSync: any
  export const FolderTree: any
  export const FolderUp: any
  export const FolderX: any
  export const Folders: any
  export const Footprints: any
  export const Forklift: any
  export const Forward: any
  export const Frame: any
  export const Framer: any
  export const Frown: any
  export const Fuel: any
  export const Fullscreen: any
  export const GalleryHorizontal: any
  export const GalleryHorizontalEnd: any
  export const GalleryThumbnails: any
  export const GalleryVertical: any
  export const GalleryVerticalEnd: any
  export const Gamepad: any
  export const Gamepad2: any
  export const Gauge: any
  export const Gavel: any
  export const Gem: any
  export const Ghost: any
  export const Gift: any
  export const GitBranch: any
  export const GitBranchPlus: any
  export const GitCommitHorizontal: any
  export const GitCommitVertical: any
  export const GitCompare: any
  export const GitCompareArrows: any
  export const GitFork: any
  export const GitGraph: any
  export const GitMerge: any
  export const GitPullRequest: any
  export const GitPullRequestArrow: any
  export const GitPullRequestClosed: any
  export const GitPullRequestCreate: any
  export const GitPullRequestCreateArrow: any
  export const GitPullRequestDraft: any
  export const Github: any
  export const Gitlab: any
  export const GlassWater: any
  export const Glasses: any
  export const Globe: any
  export const Globe2: any
  export const GlobeLock: any
  export const Goal: any
  export const Grab: any
  export const GraduationCap: any
  export const Grape: any
  export const Grid: any
  export const Grid2x2: any
  export const Grid2x2Check: any
  export const Grid2x2Plus: any
  export const Grid2x2X: any
  export const Grid3x3: any
  export const GripHorizontal: any
  export const GripVertical: any
  export const Group: any
  export const Guitar: any
  export const Ham: any
  export const Hammer: any
  export const Hand: any
  export const HandCoins: any
  export const HandHeart: any
  export const HandHelping: any
  export const HandMetal: any
  export const HandPlatter: any
  export const Handshake: any
  export const HardDrive: any
  export const HardDriveDownload: any
  export const HardDriveUpload: any
  export const HardHat: any
  export const Hash: any
  export const Haze: any
  export const HdmiPort: any
  export const Heading: any
  export const Heading1: any
  export const Heading2: any
  export const Heading3: any
  export const Heading4: any
  export const Heading5: any
  export const Heading6: any
  export const HeadphoneOff: any
  export const Headphones: any
  export const Headset: any
  export const Heart: any
  export const HeartCrack: any
  export const HeartHandshake: any
  export const HeartOff: any
  export const HeartPulse: any
  export const Heater: any
  export const Hexagon: any
  export const Highlighter: any
  export const History: any
  export const Home: any
  export const Hop: any
  export const HopOff: any
  export const Hospital: any
  export const Hotel: any
  export const Hourglass: any
  export const House: any
  export const HousePlug: any
  export const HousePlus: any
  export const IceCreamBowl: any
  export const IceCreamCone: any
  export const IdCard: any
  export const Image: any
  export const ImageDown: any
  export const ImageMinus: any
  export const ImageOff: any
  export const ImagePlay: any
  export const ImagePlus: any
  export const ImageUp: any
  export const ImageUpscale: any
  export const Images: any
  export const Import: any
  export const Inbox: any
  export const IndentDecrease: any
  export const IndentIncrease: any
  export const IndianRupee: any
  export const InfinityIcon: any
  export const Info: any
  export const InspectionPanel: any
  export const Instagram: any
  export const Italic: any
  export const IterationCcw: any
  export const IterationCw: any
  export const JapaneseYen: any
  export const Joystick: any
  export const Kanban: any
  export const Key: any
  export const KeyRound: any
  export const KeySquare: any
  export const Keyboard: any
  export const KeyboardMusic: any
  export const KeyboardOff: any
  export const Lamp: any
  export const LampCeiling: any
  export const LampDesk: any
  export const LampFloor: any
  export const LampWallDown: any
  export const LampWallUp: any
  export const LandPlot: any
  export const Landmark: any
  export const Languages: any
  export const Laptop: any
  export const Laptop2: any
  export const LaptopMinimal: any
  export const LaptopMinimalCheck: any
  export const Lasso: any
  export const LassoSelect: any
  export const Laugh: any
  export const Layers: any
  export const Layers2: any
  export const Layers3: any
  export const Layout: any
  export const LayoutDashboard: any
  export const LayoutGrid: any
  export const LayoutList: any
  export const LayoutPanelLeft: any
  export const LayoutPanelTop: any
  export const LayoutTemplate: any
  export const Leaf: any
  export const LeafyGreen: any
  export const Lectern: any
  export const LetterText: any
  export const Library: any
  export const LibraryBig: any
  export const LifeBuoy: any
  export const Ligature: any
  export const Lightbulb: any
  export const LightbulbOff: any
  export const LineChart: any
  export const Link: any
  export const Link2: any
  export const Link2Off: any
  export const Linkedin: any
  export const List: any
  export const ListCheck: any
  export const ListChecks: any
  export const ListCollapse: any
  export const ListEnd: any
  export const ListFilter: any
  export const ListMinus: any
  export const ListMusic: any
  export const ListOrdered: any
  export const ListPlus: any
  export const ListRestart: any
  export const ListStart: any
  export const ListTodo: any
  export const ListTree: any
  export const ListVideo: any
  export const ListX: any
  export const Loader: any
  export const Loader2: any
  export const LoaderCircle: any
  export const LoaderPinwheel: any
  export const Locate: any
  export const LocateFixed: any
  export const LocateOff: any
  export const Lock: any
  export const LockKeyhole: any
  export const LockKeyholeOpen: any
  export const LockOpen: any
  export const LogIn: any
  export const LogOut: any
  export const Logs: any
  export const Lollipop: any
  export const Luggage: any
  export const Magnet: any
  export const Mail: any
  export const MailCheck: any
  export const MailMinus: any
  export const MailOpen: any
  export const MailPlus: any
  export const MailQuestion: any
  export const MailSearch: any
  export const MailWarning: any
  export const MailX: any
  export const Mailbox: any
  export const Mails: any
  export const Map: any
  export const MapPin: any
  export const MapPinCheckInside: any
  export const MapPinHouse: any
  export const MapPinMinus: any
  export const MapPinMinusInside: any
  export const MapPinOff: any
  export const MapPinPlus: any
  export const MapPinPlusInside: any
  export const MapPinX: any
  export const MapPinXInside: any
  export const MapPinned: any
  export const Martini: any
  export const Maximize: any
  export const Maximize2: any
  export const Medal: any
  export const Megaphone: any
  export const MegaphoneOff: any
  export const Meh: any
  export const MemoryStick: any
  export const Menu: any
  export const MenuSquare: any
  export const Merge: any
  export const MessageCircle: any
  export const MessageCircleCode: any
  export const MessageCircleDashed: any
  export const MessageCircleHeart: any
  export const MessageCircleMore: any
  export const MessageCircleOff: any
  export const MessageCirclePlus: any
  export const MessageCircleQuestion: any
  export const MessageCircleReply: any
  export const MessageCircleWarning: any
  export const MessageCircleX: any
  export const MessageSquare: any
  export const MessageSquareCode: any
  export const MessageSquareDashed: any
  export const MessageSquareDiff: any
  export const MessageSquareDot: any
  export const MessageSquareHeart: any
  export const MessageSquareLock: any
  export const MessageSquareMore: any
  export const MessageSquareOff: any
  export const MessageSquarePlus: any
  export const MessageSquareQuote: any
  export const MessageSquareReply: any
  export const MessageSquareShare: any
  export const MessageSquareText: any
  export const MessageSquareWarning: any
  export const MessageSquareX: any
  export const MessagesSquare: any
  export const Mic: any
  export const Mic2: any
  export const MicOff: any
  export const MicVocal: any
  export const Microchip: any
  export const Microscope: any
  export const Microwave: any
  export const Milestone: any
  export const Milk: any
  export const MilkOff: any
  export const Minimize: any
  export const Minimize2: any
  export const Minus: any
  export const MinusCircle: any
  export const MinusSquare: any
  export const Monitor: any
  export const MonitorCheck: any
  export const MonitorCog: any
  export const MonitorDot: any
  export const MonitorDown: any
  export const MonitorOff: any
  export const MonitorPause: any
  export const MonitorPlay: any
  export const MonitorSmartphone: any
  export const MonitorSpeaker: any
  export const MonitorStop: any
  export const MonitorUp: any
  export const MonitorX: any
  export const Moon: any
  export const MoonStar: any
  export const MoreHorizontal: any
  export const MoreVertical: any
  export const Mountain: any
  export const MountainSnow: any
  export const Mouse: any
  export const MouseOff: any
  export const MousePointer: any
  export const MousePointer2: any
  export const MousePointerBan: any
  export const MousePointerClick: any
  export const Move: any
  export const Move3d: any
  export const MoveDiagonal: any
  export const MoveDiagonal2: any
  export const MoveDown: any
  export const MoveDownLeft: any
  export const MoveDownRight: any
  export const MoveHorizontal: any
  export const MoveLeft: any
  export const MoveRight: any
  export const MoveUp: any
  export const MoveUpLeft: any
  export const MoveUpRight: any
  export const MoveVertical: any
  export const Music: any
  export const Music2: any
  export const Music3: any
  export const Music4: any
  export const Navigation: any
  export const Navigation2: any
  export const Navigation2Off: any
  export const NavigationOff: any
  export const Network: any
  export const Newspaper: any
  export const Nfc: any
  export const Notebook: any
  export const NotebookPen: any
  export const NotebookTabs: any
  export const NotebookText: any
  export const NotepadText: any
  export const NotepadTextDashed: any
  export const Nut: any
  export const NutOff: any
  export const Octagon: any
  export const OctagonAlert: any
  export const OctagonMinus: any
  export const OctagonPause: any
  export const OctagonX: any
  export const Omega: any
  export const Option: any
  export const Orbit: any
  export const Origami: any
  export const Package: any
  export const Package2: any
  export const PackageCheck: any
  export const PackageMinus: any
  export const PackageOpen: any
  export const PackagePlus: any
  export const PackageSearch: any
  export const PackageX: any
  export const PaintBucket: any
  export const PaintRoller: any
  export const Paintbrush: any
  export const Paintbrush2: any
  export const PaintbrushVertical: any
  export const Palette: any
  export const PanelBottom: any
  export const PanelBottomClose: any
  export const PanelBottomDashed: any
  export const PanelBottomOpen: any
  export const PanelLeft: any
  export const PanelLeftClose: any
  export const PanelLeftDashed: any
  export const PanelLeftOpen: any
  export const PanelRight: any
  export const PanelRightClose: any
  export const PanelRightDashed: any
  export const PanelRightOpen: any
  export const PanelTop: any
  export const PanelTopClose: any
  export const PanelTopDashed: any
  export const PanelTopOpen: any
  export const PanelsLeftBottom: any
  export const PanelsRightBottom: any
  export const PanelsTopLeft: any
  export const Paperclip: any
  export const Parentheses: any
  export const ParkingMeter: any
  export const PartyPopper: any
  export const Pause: any
  export const PawPrint: any
  export const PcCase: any
  export const Pen: any
  export const PenLine: any
  export const PenOff: any
  export const PenTool: any
  export const Pencil: any
  export const PencilLine: any
  export const PencilOff: any
  export const PencilRuler: any
  export const Pentagon: any
  export const Percent: any
  export const PersonStanding: any
  export const Phone: any
  export const PhoneCall: any
  export const PhoneForwarded: any
  export const PhoneIncoming: any
  export const PhoneMissed: any
  export const PhoneOff: any
  export const PhoneOutgoing: any
  export const Pi: any
  export const Piano: any
  export const Pickaxe: any
  export const PictureInPicture: any
  export const PictureInPicture2: any
  export const PiggyBank: any
  export const Pilcrow: any
  export const PilcrowLeft: any
  export const PilcrowRight: any
  export const Pill: any
  export const PillBottle: any
  export const Pin: any
  export const PinOff: any
  export const Pipette: any
  export const Pizza: any
  export const Plane: any
  export const PlaneLanding: any
  export const PlaneTakeoff: any
  export const Play: any
  export const PlayCircle: any
  export const PlaySquare: any
  export const Plug: any
  export const Plug2: any
  export const PlugZap: any
  export const Plus: any
  export const PlusCircle: any
  export const PlusSquare: any
  export const Pocket: any
  export const PocketKnife: any
  export const Podcast: any
  export const Pointer: any
  export const PointerOff: any
  export const Popcorn: any
  export const Popsicle: any
  export const PoundSterling: any
  export const Power: any
  export const PowerOff: any
  export const Presentation: any
  export const Printer: any
  export const PrinterCheck: any
  export const Projector: any
  export const Proportions: any
  export const Puzzle: any
  export const Pyramid: any
  export const QrCode: any
  export const Quote: any
  export const Rabbit: any
  export const Radar: any
  export const Radiation: any
  export const Radical: any
  export const Radio: any
  export const RadioReceiver: any
  export const RadioTower: any
  export const Radius: any
  export const RailSymbol: any
  export const Rainbow: any
  export const Rat: any
  export const Ratio: any
  export const Receipt: any
  export const ReceiptCent: any
  export const ReceiptEuro: any
  export const ReceiptIndianRupee: any
  export const ReceiptJapaneseYen: any
  export const ReceiptPoundSterling: any
  export const ReceiptRussianRuble: any
  export const ReceiptSwissFranc: any
  export const ReceiptText: any
  export const RectangleEllipsis: any
  export const RectangleHorizontal: any
  export const RectangleVertical: any
  export const Recycle: any
  export const Redo: any
  export const Redo2: any
  export const RedoDot: any
  export const RefreshCcw: any
  export const RefreshCcwDot: any
  export const RefreshCw: any
  export const RefreshCwOff: any
  export const Refrigerator: any
  export const Regex: any
  export const RemoveFormatting: any
  export const Repeat: any
  export const Repeat1: any
  export const Repeat2: any
  export const Replace: any
  export const ReplaceAll: any
  export const Reply: any
  export const ReplyAll: any
  export const Rewind: any
  export const Ribbon: any
  export const Rocket: any
  export const RockingChair: any
  export const RollerCoaster: any
  export const Rotate3d: any
  export const RotateCcw: any
  export const RotateCcwSquare: any
  export const RotateCw: any
  export const RotateCwSquare: any
  export const Route: any
  export const RouteOff: any
  export const Router: any
  export const Rows2: any
  export const Rows3: any
  export const Rows4: any
  export const Rss: any
  export const Ruler: any
  export const RussianRuble: any
  export const Sailboat: any
  export const Salad: any
  export const Sandwich: any
  export const Satellite: any
  export const SatelliteDish: any
  export const Save: any
  export const SaveAll: any
  export const SaveOff: any
  export const Scale: any
  export const Scale3d: any
  export const Scaling: any
  export const Scan: any
  export const ScanBarcode: any
  export const ScanEye: any
  export const ScanFace: any
  export const ScanLine: any
  export const ScanQrCode: any
  export const ScanSearch: any
  export const ScanText: any
  export const School: any
  export const Scissors: any
  export const ScissorsLineDashed: any
  export const ScreenShare: any
  export const ScreenShareOff: any
  export const Scroll: any
  export const ScrollText: any
  export const Search: any
  export const SearchCheck: any
  export const SearchCode: any
  export const SearchSlash: any
  export const SearchX: any
  export const Section: any
  export const Send: any
  export const SendHorizontal: any
  export const SendToBack: any
  export const SeparatorHorizontal: any
  export const SeparatorVertical: any
  export const Server: any
  export const ServerCog: any
  export const ServerCrash: any
  export const ServerOff: any
  export const Settings: any
  export const Settings2: any
  export const Shapes: any
  export const Share: any
  export const Share2: any
  export const Sheet: any
  export const Shell: any
  export const Shield: any
  export const ShieldAlert: any
  export const ShieldBan: any
  export const ShieldCheck: any
  export const ShieldEllipsis: any
  export const ShieldHalf: any
  export const ShieldMinus: any
  export const ShieldOff: any
  export const ShieldPlus: any
  export const ShieldQuestion: any
  export const ShieldX: any
  export const Ship: any
  export const ShipWheel: any
  export const Shirt: any
  export const ShoppingBag: any
  export const ShoppingBasket: any
  export const ShoppingCart: any
  export const Shovel: any
  export const ShowerHead: any
  export const Shrink: any
  export const Shrub: any
  export const Shuffle: any
  export const Sigma: any
  export const Signal: any
  export const SignalHigh: any
  export const SignalLow: any
  export const SignalMedium: any
  export const SignalZero: any
  export const Signature: any
  export const Signpost: any
  export const SignpostBig: any
  export const Siren: any
  export const SkipBack: any
  export const SkipForward: any
  export const Skull: any
  export const Slack: any
  export const Slash: any
  export const SlashSquare: any
  export const Slice: any
  export const SlidersHorizontal: any
  export const SlidersVertical: any
  export const Smartphone: any
  export const SmartphoneCharging: any
  export const SmartphoneNfc: any
  export const Smile: any
  export const SmilePlus: any
  export const Snail: any
  export const Snowflake: any
  export const Sofa: any
  export const Soup: any
  export const Space: any
  export const Spade: any
  export const Sparkle: any
  export const Sparkles: any
  export const Speaker: any
  export const Speech: any
  export const SpellCheck: any
  export const SpellCheck2: any
  export const Spline: any
  export const Split: any
  export const SprayCan: any
  export const Sprout: any
  export const Square: any
  export const SquareActivity: any
  export const SquareArrowDown: any
  export const SquareArrowDownLeft: any
  export const SquareArrowDownRight: any
  export const SquareArrowLeft: any
  export const SquareArrowOutDownLeft: any
  export const SquareArrowOutDownRight: any
  export const SquareArrowOutUpLeft: any
  export const SquareArrowOutUpRight: any
  export const SquareArrowRight: any
  export const SquareArrowUp: any
  export const SquareArrowUpLeft: any
  export const SquareArrowUpRight: any
  export const SquareAsterisk: any
  export const SquareBottomDashedScissors: any
  export const SquareChart: any
  export const SquareChartGantt: any
  export const SquareCheck: any
  export const SquareCheckBig: any
  export const SquareChevronDown: any
  export const SquareChevronLeft: any
  export const SquareChevronRight: any
  export const SquareChevronUp: any
  export const SquareCode: any
  export const SquareDashed: any
  export const SquareDashedBottom: any
  export const SquareDashedBottomCode: any
  export const SquareDashedKanban: any
  export const SquareDashedMousePointer: any
  export const SquareDivide: any
  export const SquareDot: any
  export const SquareEqual: any
  export const SquareFunction: any
  export const SquareKanban: any
  export const SquareLibrary: any
  export const SquareM: any
  export const SquareMenu: any
  export const SquareMinus: any
  export const SquareMousePointer: any
  export const SquareParkingOff: any
  export const SquareParking: any
  export const SquarePen: any
  export const SquarePercent: any
  export const SquarePi: any
  export const SquarePilcrow: any
  export const SquarePlay: any
  export const SquarePlus: any
  export const SquarePower: any
  export const SquareRadical: any
  export const SquareScissors: any
  export const SquareSigma: any
  export const SquareSlash: any
  export const SquareSplitHorizontal: any
  export const SquareSplitVertical: any
  export const SquareSquare: any
  export const SquareStack: any
  export const SquareTerminal: any
  export const SquareUser: any
  export const SquareUserRound: any
  export const SquareX: any
  export const Squircle: any
  export const Squirrel: any
  export const Stamp: any
  export const Star: any
  export const StarHalf: any
  export const StarOff: any
  export const Stars: any
  export const StepBack: any
  export const StepForward: any
  export const Stethoscope: any
  export const Sticker: any
  export const StickyNote: any
  export const StopCircle: any
  export const Store: any
  export const StretchHorizontal: any
  export const StretchVertical: any
  export const Strikethrough: any
  export const Subscript: any
  export const Subtitles: any
  export const Sun: any
  export const SunDim: any
  export const SunMedium: any
  export const SunMoon: any
  export const SunSnow: any
  export const Sunrise: any
  export const Sunset: any
  export const Superscript: any
  export const SwatchBook: any
  export const SwissFranc: any
  export const SwitchCamera: any
  export const Sword: any
  export const Swords: any
  export const Syringe: any
  export const Table: any
  export const Table2: any
  export const TableCellsMerge: any
  export const TableCellsSplit: any
  export const TableColumnsSplit: any
  export const TableOfContents: any
  export const TableProperties: any
  export const TableRowsSplit: any
  export const Tablet: any
  export const TabletSmartphone: any
  export const Tablets: any
  export const Tag: any
  export const Tags: any
  export const Tally1: any
  export const Tally2: any
  export const Tally3: any
  export const Tally4: any
  export const Tally5: any
  export const Tangent: any
  export const Target: any
  export const Telescope: any
  export const Tent: any
  export const TentTree: any
  export const Terminal: any
  export const TerminalSquare: any
  export const TestTube: any
  export const TestTubeDiagonal: any
  export const TestTubes: any
  export const Text: any
  export const TextCursor: any
  export const TextCursorInput: any
  export const TextQuote: any
  export const TextSearch: any
  export const TextSelect: any
  export const Theater: any
  export const Thermometer: any
  export const ThermometerSnowflake: any
  export const ThermometerSun: any
  export const ThumbsDown: any
  export const ThumbsUp: any
  export const Ticket: any
  export const TicketCheck: any
  export const TicketMinus: any
  export const TicketPercent: any
  export const TicketPlus: any
  export const TicketSlash: any
  export const TicketX: any
  export const Tickets: any
  export const TicketsPlane: any
  export const Timer: any
  export const TimerOff: any
  export const TimerReset: any
  export const ToggleLeft: any
  export const ToggleRight: any
  export const Toilet: any
  export const Tornado: any
  export const Torus: any
  export const Touchpad: any
  export const TouchpadOff: any
  export const TowerControl: any
  export const ToyBrick: any
  export const Tractor: any
  export const TrafficCone: any
  export const Train: any
  export const TrainFront: any
  export const TrainFrontTunnel: any
  export const TrainTrack: any
  export const TramFront: any
  export const Trash: any
  export const Trash2: any
  export const TreeDeciduous: any
  export const TreePalm: any
  export const TreePine: any
  export const Trees: any
  export const Trello: any
  export const TrendingDown: any
  export const TrendingUp: any
  export const TrendingUpDown: any
  export const Triangle: any
  export const TriangleAlert: any
  export const TriangleRight: any
  export const Trophy: any
  export const Truck: any
  export const Turtle: any
  export const Tv: any
  export const TvMinimal: any
  export const TvMinimalPlay: any
  export const Twitch: any
  export const Twitter: any
  export const Type: any
  export const TypeOutline: any
  export const Umbrella: any
  export const UmbrellaOff: any
  export const Underline: any
  export const Undo: any
  export const Undo2: any
  export const UndoDot: any
  export const UnfoldHorizontal: any
  export const UnfoldVertical: any
  export const Ungroup: any
  export const University: any
  export const Unlink: any
  export const Unlink2: any
  export const Unlock: any
  export const Unplug: any
  export const Upload: any
  export const UploadCloud: any
  export const Usb: any
  export const User: any
  export const UserCheck: any
  export const UserCog: any
  export const UserMinus: any
  export const UserPen: any
  export const UserPlus: any
  export const UserRound: any
  export const UserRoundCheck: any
  export const UserRoundCog: any
  export const UserRoundMinus: any
  export const UserRoundPen: any
  export const UserRoundPlus: any
  export const UserRoundSearch: any
  export const UserRoundX: any
  export const UserSearch: any
  export const UserX: any
  export const Users: any
  export const UsersRound: any
  export const Utensils: any
  export const UtensilsCrossed: any
  export const UtilityPole: any
  export const Variable: any
  export const Vault: any
  export const Vegan: any
  export const VenetianMask: any
  export const Vibrate: any
  export const VibrateOff: any
  export const Video: any
  export const VideoOff: any
  export const Videotape: any
  export const View: any
  export const Voicemail: any
  export const Volleyball: any
  export const Volume: any
  export const Volume1: any
  export const Volume2: any
  export const VolumeOff: any
  export const VolumeX: any
  export const Vote: any
  export const Wallet: any
  export const WalletCards: any
  export const WalletMinimal: any
  export const Wallpaper: any
  export const Wand: any
  export const WandSparkles: any
  export const Warehouse: any
  export const WashingMachine: any
  export const Watch: any
  export const Waves: any
  export const WavesLadder: any
  export const Waypoints: any
  export const Webcam: any
  export const Webhook: any
  export const WebhookOff: any
  export const Weight: any
  export const Wheat: any
  export const WheatOff: any
  export const WholeWord: any
  export const Wifi: any
  export const WifiHigh: any
  export const WifiLow: any
  export const WifiOff: any
  export const WifiZero: any
  export const Wind: any
  export const Wine: any
  export const WineOff: any
  export const Workflow: any
  export const WrapText: any
  export const Wrench: any
  export const X: any
  export const XCircle: any
  export const XOctagon: any
  export const XSquare: any
  export const Youtube: any
  export const Zap: any
  export const ZapOff: any
  export const ZoomIn: any
  export const ZoomOut: any
  export const ImageIcon: any
  export const ArrowDown: any
  export const Sidebar: any
  export const ArrowUpRight: any
  export const ArrowUp: any
  export const UserIcon: any
  export const FileTextIcon: any
}