/**
 * Cosmetics Signage Playlist Management Page
 *
 * Admin page for managing signage playlists for digital displays
 */

import React, { useState, useEffect } from 'react';
import { authClient } from '@o4o/auth-client';

interface PlaylistItem {
  type: 'product' | 'brand' | 'routine' | 'category';
  productId?: string;
  brandId?: string;
  routineId?: string;
  category?: string;
  duration: number;
}

interface Playlist {
  id: string;
  name: string;
  description?: string;
  items: PlaylistItem[];
  metadata: {
    autoGenerated?: boolean;
    totalDuration?: number;
  };
  createdAt: string;
  updatedAt: string;
}

export default function CosmeticsSignagePage() {
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showAutoGenerator, setShowAutoGenerator] = useState(false);

  // Auto generator form state
  const [autoFilters, setAutoFilters] = useState({
    brand: '',
    category: '',
    concerns: [] as string[],
    skinTypes: [] as string[],
    includeRoutines: false,
    maxItems: 20,
  });

  useEffect(() => {
    loadPlaylists();
  }, []);

  const loadPlaylists = async () => {
    try {
      setLoading(true);
      setError(null);

      const response = await authClient.api.get('/cosmetics/signage/playlists');

      if (response.data.success) {
        setPlaylists(response.data.data || []);
      } else {
        setError('Failed to load playlists');
      }
    } catch (err: any) {
      console.error('Error loading playlists:', err);
      setError(err.message || 'Failed to load playlists');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateAutoPlaylist = async () => {
    try {
      setLoading(true);
      setError(null);

      const response = await authClient.api.post('/cosmetics/signage/auto-playlist', autoFilters);

      if (response.data.success) {
        alert(`플레이리스트 생성 완료: ${response.data.data.totalItems}개 항목, 총 ${response.data.data.totalDuration}초`);

        // Create playlist with generated items
        const createResponse = await authClient.api.post('/cosmetics/signage/playlists', {
          name: `Auto Playlist - ${new Date().toLocaleString('ko-KR')}`,
          description: `자동 생성됨 (${autoFilters.brand || autoFilters.category || '추천'})`,
          items: response.data.data.items,
          metadata: {
            autoGenerated: true,
            filters: autoFilters,
          },
        });

        if (createResponse.data.success) {
          await loadPlaylists();
          setShowAutoGenerator(false);
        }
      }
    } catch (err: any) {
      console.error('Error generating auto playlist:', err);
      setError(err.response?.data?.message || err.message || 'Failed to generate auto playlist');
    } finally {
      setLoading(false);
    }
  };

  const handleDeletePlaylist = async (id: string) => {
    if (!confirm('정말로 이 플레이리스트를 삭제하시겠습니까?')) {
      return;
    }

    try {
      const response = await authClient.api.delete(`/cosmetics/signage/playlists/${id}`);

      if (response.data.success) {
        await loadPlaylists();
      }
    } catch (err: any) {
      console.error('Error deleting playlist:', err);
      alert(err.response?.data?.message || 'Failed to delete playlist');
    }
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold mb-2">Signage Playlist 관리</h1>
        <p className="text-gray-600">
          매장 디지털 사이니지용 플레이리스트를 관리합니다
        </p>
      </div>

      {/* Error Display */}
      {error && (
        <div className="mb-4 p-4 bg-red-100 text-red-700 rounded">
          {error}
        </div>
      )}

      {/* Action Buttons */}
      <div className="mb-6 flex gap-4">
        <button
          onClick={() => setShowAutoGenerator(!showAutoGenerator)}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          {showAutoGenerator ? '취소' : '자동 플레이리스트 생성'}
        </button>
        <button
          onClick={loadPlaylists}
          disabled={loading}
          className="px-4 py-2 bg-gray-600 text-white rounded hover:bg-gray-700 disabled:opacity-50"
        >
          새로고침
        </button>
      </div>

      {/* Auto Generator Form */}
      {showAutoGenerator && (
        <div className="mb-6 p-6 bg-white border rounded-lg shadow">
          <h2 className="text-lg font-bold mb-4">자동 플레이리스트 생성</h2>

          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-sm font-medium mb-2">브랜드</label>
              <input
                type="text"
                value={autoFilters.brand}
                onChange={(e) => setAutoFilters({ ...autoFilters, brand: e.target.value })}
                className="w-full px-3 py-2 border rounded"
                placeholder="브랜드명 (선택)"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">카테고리</label>
              <input
                type="text"
                value={autoFilters.category}
                onChange={(e) => setAutoFilters({ ...autoFilters, category: e.target.value })}
                className="w-full px-3 py-2 border rounded"
                placeholder="카테고리 (선택)"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">최대 항목 수</label>
              <input
                type="number"
                value={autoFilters.maxItems}
                onChange={(e) => setAutoFilters({ ...autoFilters, maxItems: parseInt(e.target.value) })}
                className="w-full px-3 py-2 border rounded"
                min="1"
                max="50"
              />
            </div>

            <div>
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={autoFilters.includeRoutines}
                  onChange={(e) => setAutoFilters({ ...autoFilters, includeRoutines: e.target.checked })}
                  className="rounded"
                />
                <span className="text-sm font-medium">루틴 포함</span>
              </label>
            </div>
          </div>

          <button
            onClick={handleGenerateAutoPlaylist}
            disabled={loading}
            className="w-full px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:opacity-50"
          >
            {loading ? '생성 중...' : '플레이리스트 생성'}
          </button>
        </div>
      )}

      {/* Loading State */}
      {loading && !showAutoGenerator && (
        <div className="text-center py-12">
          <div className="text-gray-500">로딩 중...</div>
        </div>
      )}

      {/* Playlists List */}
      {!loading && (
        <div>
          {playlists.length === 0 ? (
            <div className="text-center py-12 text-gray-500 bg-gray-50 rounded-lg">
              등록된 플레이리스트가 없습니다
            </div>
          ) : (
            <div className="grid gap-4">
              {playlists.map((playlist) => (
                <div key={playlist.id} className="bg-white border rounded-lg p-6 shadow-sm">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="text-lg font-bold">{playlist.name}</h3>
                        {playlist.metadata.autoGenerated && (
                          <span className="text-xs px-2 py-1 bg-blue-100 text-blue-800 rounded">
                            자동생성
                          </span>
                        )}
                      </div>
                      {playlist.description && (
                        <p className="text-sm text-gray-600 mt-1">{playlist.description}</p>
                      )}
                    </div>
                    <button
                      onClick={() => handleDeletePlaylist(playlist.id)}
                      className="text-red-600 hover:text-red-900"
                    >
                      삭제
                    </button>
                  </div>

                  <div className="grid grid-cols-3 gap-4 mb-4 text-sm">
                    <div>
                      <span className="text-gray-600">항목 수:</span>{' '}
                      <span className="font-medium">{playlist.items.length}개</span>
                    </div>
                    <div>
                      <span className="text-gray-600">총 재생시간:</span>{' '}
                      <span className="font-medium">{playlist.metadata.totalDuration || 0}초</span>
                    </div>
                    <div>
                      <span className="text-gray-600">업데이트:</span>{' '}
                      <span className="font-medium">
                        {new Date(playlist.updatedAt).toLocaleDateString('ko-KR')}
                      </span>
                    </div>
                  </div>

                  <div className="border-t pt-4">
                    <h4 className="text-sm font-medium mb-2">플레이리스트 항목</h4>
                    <div className="flex flex-wrap gap-2">
                      {playlist.items.slice(0, 10).map((item, idx) => (
                        <span
                          key={idx}
                          className="inline-flex items-center px-3 py-1 rounded-full text-xs bg-gray-100"
                        >
                          {item.type === 'product' && '제품'}
                          {item.type === 'brand' && '브랜드'}
                          {item.type === 'routine' && '루틴'}
                          {item.type === 'category' && '카테고리'}
                          <span className="ml-1 text-gray-600">({item.duration}초)</span>
                        </span>
                      ))}
                      {playlist.items.length > 10 && (
                        <span className="text-xs text-gray-500">
                          +{playlist.items.length - 10}개 더
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
