import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Users, UserCheck, UserPlus, ArrowUpRight, ArrowDownRight, AlertCircle } from 'lucide-react';
const UserStats = ({ data, isLoading = false }) => {
    if (isLoading) {
        return (_jsx("div", { className: "wp-card animate-pulse", children: _jsxs("div", { className: "wp-card-body", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "h-4 bg-gray-200 rounded w-20 mb-2" }), _jsx("div", { className: "h-8 bg-gray-200 rounded w-16" })] }), _jsx("div", { className: "w-12 h-12 bg-gray-200 rounded-lg" })] }), _jsx("div", { className: "mt-4", children: _jsx("div", { className: "h-4 bg-gray-200 rounded w-24" }) })] }) }));
    }
    const { total = 0, pending = 0, today = 0, activeRate = 0, change = 0, trend = 'up' } = data || {};
    const formatNumber = (num) => {
        return new Intl.NumberFormat('ko-KR').format(num);
    };
    const formatPercentage = (num) => {
        return `${num.toFixed(1)}%`;
    };
    return (_jsx("div", { className: "wp-card hover:shadow-md transition-shadow duration-200", children: _jsxs("div", { className: "wp-card-body", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("h3", { className: "text-sm font-medium text-gray-600", children: "\uC804\uCCB4 \uC0AC\uC6A9\uC790" }), pending > 0 && (_jsxs("div", { className: "ml-2 flex items-center", children: [_jsx(AlertCircle, { className: "w-3 h-3 text-red-500" }), _jsxs("span", { className: "text-xs text-red-600 ml-1", children: [pending, "\uBA85 \uC2B9\uC778 \uB300\uAE30"] })] }))] }), _jsx("p", { className: "text-2xl font-bold text-gray-900 mt-1", children: formatNumber(total) })] }), _jsx("div", { className: "w-12 h-12 bg-blue-50 rounded-lg flex items-center justify-center", children: _jsx(Users, { className: "w-6 h-6 text-blue-600" }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3 mb-4", children: [_jsxs("div", { className: "bg-gray-50 rounded p-2", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(UserPlus, { className: "w-3 h-3 text-green-600 mr-1" }), _jsx("span", { className: "text-xs text-gray-600", children: "\uC624\uB298 \uAC00\uC785" })] }), _jsxs("p", { className: "text-sm font-semibold text-gray-900", children: [formatNumber(today), "\uBA85"] })] }), _jsxs("div", { className: "bg-gray-50 rounded p-2", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(UserCheck, { className: "w-3 h-3 text-blue-600 mr-1" }), _jsx("span", { className: "text-xs text-gray-600", children: "\uD65C\uC131\uB960" })] }), _jsx("p", { className: "text-sm font-semibold text-gray-900", children: formatPercentage(activeRate) })] })] }), _jsxs("div", { className: "flex items-center text-sm", children: [trend === 'up' ? (_jsx(ArrowUpRight, { className: "w-4 h-4 text-green-500 mr-1" })) : (_jsx(ArrowDownRight, { className: "w-4 h-4 text-red-500 mr-1" })), _jsx("span", { className: `font-medium ${trend === 'up' ? 'text-green-600' : 'text-red-600'}`, children: formatPercentage(Math.abs(change)) }), _jsx("span", { className: "text-gray-500 ml-1", children: "\uC9C0\uB09C \uB2EC \uB300\uBE44" })] }), pending > 0 && (_jsx("div", { className: "mt-3 p-2 bg-red-50 border border-red-200 rounded-md", children: _jsxs("div", { className: "flex items-center text-xs text-red-700", children: [_jsx(AlertCircle, { className: "w-3 h-3 mr-1" }), _jsxs("span", { children: [_jsxs("strong", { children: [pending, "\uBA85"] }), "\uC758 \uC0AC\uC6A9\uC790\uAC00 \uC2B9\uC778\uC744 \uAE30\uB2E4\uB9AC\uACE0 \uC788\uC2B5\uB2C8\uB2E4"] })] }) }))] }) }));
};
export default UserStats;
//# sourceMappingURL=UserStats.js.map