/**
 * Cosmetics API Types
 *
 * ⚠️ 자동 생성 파일 - 직접 수정 금지 ⚠️
 *
 * 이 파일은 OpenAPI 스펙에서 자동 생성됩니다.
 * 변경이 필요하면 OpenAPI 스펙을 수정하고 재생성하세요.
 *
 * Source: docs\services\cosmetics\openapi.yaml
 * Generated: 2025-12-29T12:26:37.425Z
 * Generator: scripts/generators/openapi-types-generator.ts
 *
 * 관련 규칙: CLAUDE.md §21
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cosmetics/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 목록 조회
         * @description 페이지네이션을 지원하는 상품 목록 조회
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 상세 조회
         * @description 단일 상품의 상세 정보 조회
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 검색
         * @description 키워드 기반 상품 검색
         */
        get: operations["searchProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 상품 등록
         * @description 새 상품 등록 (Admin 권한 필요)
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 상품 수정
         * @description 기존 상품 정보 수정 (Admin 권한 필요)
         */
        put: operations["updateProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/products/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 상품 상태 변경
         * @description 상품 상태 변경 (Admin 권한 필요)
         *
         *     허용 전이:
         *     - draft → visible, hidden
         *     - visible → hidden, sold_out
         *     - hidden → visible, sold_out
         *     - sold_out → visible, hidden
         */
        patch: operations["updateProductStatus"];
        trace?: never;
    };
    "/cosmetics/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 브랜드 목록 조회
         * @description 활성 브랜드 목록 조회
         */
        get: operations["listBrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 브랜드 상세 조회
         * @description 단일 브랜드의 상세 정보 및 라인 목록 조회
         */
        get: operations["getBrand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 라인 목록 조회
         * @description 브랜드별 라인 목록 조회
         */
        get: operations["listLines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/prices/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가격 정책 조회
         * @description 상품의 가격 정책 조회 (Admin 권한 필요)
         */
        get: operations["getPricePolicy"];
        /**
         * 가격 정책 수정
         * @description 상품의 가격 정책 수정 (Admin 권한 필요)
         */
        put: operations["updatePricePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/logs/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 변경 이력 조회
         * @description 상품 변경 감사 로그 조회 (Admin 권한 필요)
         */
        get: operations["getProductLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cosmetics/admin/logs/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가격 변경 이력 조회
         * @description 가격 변경 감사 로그 조회 (Admin 권한 필요)
         */
        get: operations["getPriceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 상품 상태
         *     - draft: 초안 (비공개)
         *     - visible: 공개
         *     - hidden: 숨김
         *     - sold_out: 품절
         * @enum {string}
         */
        ProductStatus: "draft" | "visible" | "hidden" | "sold_out";
        /**
         * @default KRW
         * @enum {string}
         */
        Currency: "KRW" | "USD";
        PaginationMeta: {
            page: number;
            limit: number;
            total: number;
            total_pages: number;
            has_next?: boolean;
            has_prev?: boolean;
        };
        ErrorResponse: {
            error: {
                /** @description 에러 코드 (COSMETICS_XXX) */
                code: string;
                /** @description 에러 메시지 */
                message: string;
                /** @description 추가 에러 정보 */
                details?: Record<string, never>;
            };
        };
        BrandSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        BrandDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            /** Format: uri */
            logo_url?: string;
            is_active: boolean;
            lines?: components["schemas"]["LineSummary"][];
            product_count?: number;
        };
        BrandListResponse: {
            data: components["schemas"]["BrandDetail"][];
        };
        BrandDetailResponse: {
            data: components["schemas"]["BrandDetail"];
        };
        LineSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            product_count?: number;
        };
        LineListResponse: {
            data: components["schemas"]["LineSummary"][];
        };
        Price: {
            /** @description 기본 가격 */
            base: number;
            /** @description 할인 가격 */
            sale?: number | null;
            currency: components["schemas"]["Currency"];
        };
        ProductImage: {
            /** Format: uri */
            url: string;
            alt?: string;
            is_primary: boolean;
            order?: number;
        };
        ProductVariant: {
            /** Format: uuid */
            id: string;
            name: string;
            sku: string;
            /** @default 0 */
            price_modifier: number;
        };
        ProductSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            brand: components["schemas"]["BrandSummary"];
            line?: components["schemas"]["LineSummary"];
            description?: string;
            status: components["schemas"]["ProductStatus"];
            price: components["schemas"]["Price"];
            images?: components["schemas"]["ProductImage"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            brand: components["schemas"]["BrandDetail"];
            line?: components["schemas"]["LineSummary"];
            description?: string;
            ingredients?: string[];
            status: components["schemas"]["ProductStatus"];
            price: components["schemas"]["Price"];
            variants?: components["schemas"]["ProductVariant"][];
            images?: components["schemas"]["ProductImage"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductListResponse: {
            data: components["schemas"]["ProductSummary"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ProductDetailResponse: {
            data: components["schemas"]["ProductDetail"];
        };
        CreateProductRequest: {
            name: string;
            /** Format: uuid */
            brand_id: string;
            /** Format: uuid */
            line_id?: string;
            description?: string;
            ingredients?: string[];
            price: {
                base: number;
                sale?: number | null;
            };
            status?: components["schemas"]["ProductStatus"];
        };
        UpdateProductRequest: {
            name?: string;
            /** Format: uuid */
            brand_id?: string;
            /** Format: uuid */
            line_id?: string;
            description?: string;
            ingredients?: string[];
        };
        UpdateStatusRequest: {
            status: components["schemas"]["ProductStatus"];
            reason?: string;
        };
        StatusChangeResponse: {
            data: {
                /** Format: uuid */
                id: string;
                status: components["schemas"]["ProductStatus"];
                previous_status: components["schemas"]["ProductStatus"];
                /** Format: date-time */
                changed_at: string;
                /** Format: uuid */
                changed_by?: string;
            };
        };
        UpdatePricePolicyRequest: {
            base_price: number;
            sale_price?: number | null;
            /** Format: date-time */
            sale_start_at?: string | null;
            /** Format: date-time */
            sale_end_at?: string | null;
        };
        PricePolicyResponse: {
            data: {
                /** Format: uuid */
                product_id: string;
                base_price: number;
                sale_price?: number | null;
                sale_active?: boolean;
                /** Format: date-time */
                sale_start_at?: string | null;
                /** Format: date-time */
                sale_end_at?: string | null;
                /** Format: date-time */
                updated_at: string;
            };
        };
        AuditLogEntry: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            action: "CREATE" | "UPDATE" | "DELETE" | "STATUS_CHANGE";
            entity_type: string;
            /** Format: uuid */
            entity_id: string;
            changes?: Record<string, never>;
            /** Format: uuid */
            user_id?: string;
            user_name?: string;
            /** Format: date-time */
            created_at: string;
        };
        AuditLogListResponse: {
            data: components["schemas"]["AuditLogEntry"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description 잘못된 요청 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Validation failed",
                 *         "details": {
                 *           "fields": {
                 *             "name": "Name is required"
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 인증 필요 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COSMETICS_401",
                 *         "message": "Authentication required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 권한 없음 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COSMETICS_403",
                 *         "message": "Permission denied"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 리소스 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COSMETICS_001",
                 *         "message": "Product not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 충돌 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COSMETICS_409",
                 *         "message": "Resource already exists"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 서버 오류 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "COSMETICS_500",
                 *         "message": "Internal server error"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지당 항목 수 */
                limit?: number;
                /** @description 브랜드 필터 */
                brand_id?: string;
                /** @description 라인 필터 */
                line_id?: string;
                /** @description 상태 필터 */
                status?: components["schemas"]["ProductStatus"];
                /** @description 정렬 필드 */
                sort?: "created_at" | "price" | "name";
                /** @description 정렬 방향 */
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 상품 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchProducts: {
        parameters: {
            query: {
                /** @description 검색 키워드 */
                q: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProductStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusRequest"];
            };
        };
        responses: {
            /** @description 상태 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listBrands: {
        parameters: {
            query?: {
                /** @description 활성 브랜드만 필터 */
                is_active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getBrand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listLines: {
        parameters: {
            query?: {
                /** @description 브랜드 필터 */
                brand_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPricePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePolicyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePricePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePricePolicyRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getProductLogs: {
        parameters: {
            query?: {
                product_id?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getPriceLogs: {
        parameters: {
            query?: {
                product_id?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
}
