#!/bin/bash

# Fix missing FC imports in admin-dashboard components
echo "Fixing missing FC imports and type annotations..."

# List of files that need FC import
files=(
  "apps/admin-dashboard/src/components/DraggableWidget.tsx"
  "apps/admin-dashboard/src/components/InlineEdit.tsx"
  "apps/admin-dashboard/src/components/ScreenOptions.tsx"
  "apps/admin-dashboard/src/components/ShortcodeReference.tsx"
  "apps/admin-dashboard/src/components/acf/RepeaterFieldEditor.tsx"
  "apps/admin-dashboard/src/components/affiliate/CommissionApprovalManager.tsx"
  "apps/admin-dashboard/src/components/affiliate/CommissionHistory.tsx"
  "apps/admin-dashboard/src/components/affiliate/ReferralLinkGenerator.tsx"
  "apps/admin-dashboard/src/components/affiliate/ReferralToolkit.tsx"
  "apps/admin-dashboard/src/components/apps/VideoCopyButton.tsx"
  "apps/admin-dashboard/src/components/common/ShareButtons.tsx"
  "apps/admin-dashboard/src/components/ecommerce/ProductCard.tsx"
  "apps/admin-dashboard/src/components/ecommerce/ProductVariantManager.tsx"
  "apps/admin-dashboard/src/components/editor/ContentTemplates.tsx"
  "apps/admin-dashboard/src/components/editor/GutenbergSidebar.tsx"
  "apps/admin-dashboard/src/components/editor/PostEditor.tsx"
  "apps/admin-dashboard/src/components/forms/FormConfirmationsTab.tsx"
  "apps/admin-dashboard/src/components/forms/FormNotificationsTab.tsx"
  "apps/admin-dashboard/src/components/layout/AdminLayout.tsx"
  "apps/admin-dashboard/src/components/media/FolderManager.tsx"
  "apps/admin-dashboard/src/components/media/MediaDetails.tsx"
  "apps/admin-dashboard/src/components/media/MediaUploadDialog.tsx"
  "apps/admin-dashboard/src/components/notifications/RealtimeNotifications.tsx"
  "apps/admin-dashboard/src/components/template/BlockEditor.tsx"
  "apps/admin-dashboard/src/components/template/TemplateLibrary.tsx"
  "apps/admin-dashboard/src/components/users/UserForm.tsx"
  "apps/admin-dashboard/src/components/users/UserRoleChangeModal.tsx"
  "apps/admin-dashboard/src/components/vendor/ProductApprovalManager.tsx"
  "apps/admin-dashboard/src/components/vendor/SupplierProductForm.tsx"
  "apps/admin-dashboard/src/components/widget/WidgetBuilder.tsx"
  "apps/admin-dashboard/src/components/widget/WidgetLibrary.tsx"
  "apps/admin-dashboard/src/contexts/ThemeContext.tsx"
  "apps/admin-dashboard/src/pages/affiliate/AffiliatePartnerForm.tsx"
  "apps/admin-dashboard/src/pages/apps/AppsManager.tsx"
  "apps/admin-dashboard/src/pages/apps/CrowdfundingProjectForm.tsx"
  "apps/admin-dashboard/src/pages/apps/CrowdfundingProjects.tsx"
  "apps/admin-dashboard/src/pages/apps/forum/ForumBoardList.tsx"
  "apps/admin-dashboard/src/pages/apps/forum/ForumCategories.tsx"
  "apps/admin-dashboard/src/pages/apps/forum/ForumPostDetail.tsx"
  "apps/admin-dashboard/src/pages/apps/forum/ForumPostForm.tsx"
  "apps/admin-dashboard/src/pages/auth/Login.tsx"
  "apps/admin-dashboard/src/pages/categories/CategoryList.tsx"
  "apps/admin-dashboard/src/pages/categories/TagList.tsx"
  "apps/admin-dashboard/src/pages/content/CPTForm.tsx"
  "apps/admin-dashboard/src/pages/content/CustomFieldBuilder.tsx"
  "apps/admin-dashboard/src/pages/content/DynamicContentList.tsx"
  "apps/admin-dashboard/src/pages/content/MediaLibrary.tsx"
  "apps/admin-dashboard/src/pages/content/PageForm.tsx"
  "apps/admin-dashboard/src/pages/content/PageList.tsx"
  "apps/admin-dashboard/src/pages/content/PostList.tsx"
  "apps/admin-dashboard/src/pages/content/TemplateManager.tsx"
  "apps/admin-dashboard/src/pages/content/WidgetManager.tsx"
  "apps/admin-dashboard/src/pages/dashboard/MainDashboard.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/ActivityFeed/ActivityItem.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/ActivityFeed/index.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/AtAGlance.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Charts/OrderChart.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Charts/SalesChart.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Charts/UserChart.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Notifications/NotificationBadge.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Notifications/NotificationItem.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/Notifications/index.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/QuickActions/ActionButton.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/StatsCards/ContentStats.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/StatsCards/PartnerStats.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/StatsCards/ProductStats.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/StatsCards/SalesStats.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/StatsCards/UserStats.tsx"
  "apps/admin-dashboard/src/pages/dashboard/components/common/RefreshButton.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/FeeManagement.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/InventoryManagement.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/OrderDetail.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/OrderStatusManagement.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/Orders.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/ProductCategories.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/Products.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/RefundManagement.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/SettlementDashboard.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/SettlementReports.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/TossPaymentsSettings.tsx"
  "apps/admin-dashboard/src/pages/ecommerce/VendorSettlements.tsx"
  "apps/admin-dashboard/src/pages/feedback/RealtimeFeedback.tsx"
  "apps/admin-dashboard/src/pages/forms/FormBuilder.tsx"
  "apps/admin-dashboard/src/pages/forms/FormList.tsx"
  "apps/admin-dashboard/src/pages/forms/FormSubmissions.tsx"
  "apps/admin-dashboard/src/pages/media/Library.tsx"
  "apps/admin-dashboard/src/pages/media/components/MediaSelector.tsx"
  "apps/admin-dashboard/src/pages/media/components/MediaUploader.tsx"
  "apps/admin-dashboard/src/pages/media/components/ResponsiveImage.tsx"
  "apps/admin-dashboard/src/pages/menus/MenuBuilder.tsx"
  "apps/admin-dashboard/src/pages/menus/Menus.tsx"
  "apps/admin-dashboard/src/pages/posts/AllPosts.tsx"
  "apps/admin-dashboard/src/pages/posts/Categories.tsx"
  "apps/admin-dashboard/src/pages/posts/Tags.tsx"
  "apps/admin-dashboard/src/pages/settings/PolicySettings.tsx"
  "apps/admin-dashboard/src/pages/settings/ThemeSettings.tsx"
  "apps/admin-dashboard/src/pages/settings/components/InventoryPolicies.tsx"
  "apps/admin-dashboard/src/pages/settings/components/PartnerPolicies.tsx"
  "apps/admin-dashboard/src/pages/settings/components/PolicyHistory.tsx"
  "apps/admin-dashboard/src/pages/settings/components/SalesTargetPolicies.tsx"
  "apps/admin-dashboard/src/pages/settings/components/UserSecurityPolicies.tsx"
  "apps/admin-dashboard/src/pages/templates/HomepageEditor.tsx"
  "apps/admin-dashboard/src/pages/templates/TemplateLayoutManager.tsx"
  "apps/admin-dashboard/src/pages/test/GutenbergPage.tsx"
  "apps/admin-dashboard/src/pages/users-backup/AddUser.tsx"
  "apps/admin-dashboard/src/pages/users-backup/AllUsers.tsx"
  "apps/admin-dashboard/src/pages/users-backup/PendingApproval.tsx"
  "apps/admin-dashboard/src/pages/users-backup/components/BulkActions.tsx"
  "apps/admin-dashboard/src/shared/components/theme/MultiThemeContext.tsx"
  "apps/admin-dashboard/src/test-utils/render.tsx"
  "apps/admin-dashboard/src/pages/Users/__tests__/UsersList.test.tsx"
)

# Add FC import to files that are missing it
for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    # Check if FC is already imported
    if ! grep -q "import.*{.*FC.*}" "$file"; then
      # Check if there's already a react import line
      if grep -q "^import.*from ['\"]react['\"]" "$file"; then
        # Add FC to existing import
        sed -i '1,/^import.*from ['"'"'"]react['"'"'"]/s/import \(.*\) from ['"'"'"]react['"'"'"]/import \1, { FC } from '"'"'react'"'"'/' "$file"
      else
        # Add new import at the beginning
        sed -i '1s/^/import { FC } from '"'"'react'"'"';\n/' "$file"
      fi
    fi
  fi
done

echo "Fixed FC imports. Now fixing other specific issues..."