import type { AnalysisProvider } from './analysis.provider.js';
import type { CareInsightDto } from './dto.js';
import type { CgmProvider } from './cgm.provider.js';
import { analyzeReadings } from './analysis.engine.js';
import { AiInsightService } from '@o4o/pharmacy-ai-insight/backend';
import type { AiInsightOutput } from '@o4o/pharmacy-ai-insight/backend';

/**
 * AiInsightProvider
 *
 * CgmProvider → AnalysisEngine (tir/cv/risk) + AI service (insights).
 *
 * - tir/cv/riskLevel: computed from real CGM readings via AnalysisEngine
 * - insights: generated by @o4o/pharmacy-ai-insight
 */
export class AiInsightProvider implements AnalysisProvider {
  private aiService: AiInsightService;

  constructor(private cgmProvider: CgmProvider) {
    this.aiService = new AiInsightService();
  }

  async analyzePatient(patientId: string): Promise<CareInsightDto> {
    const to = new Date();
    const from = new Date(to.getTime() - 14 * 24 * 60 * 60 * 1000); // 14 days

    // Parallel: CGM analysis + AI insights
    const [readings, aiResult] = await Promise.all([
      this.cgmProvider.getReadings(patientId, from, to),
      this.aiService.generateInsight({
        context: { pharmacyId: patientId },
      }),
    ]);

    const analysis = analyzeReadings(readings);
    const insights = aiResult.summaryCards.map((card) => card.content);

    return {
      patientId,
      tir: analysis.tir,
      cv: analysis.cv,
      riskLevel: analysis.riskLevel,
      insights,
    };
  }
}
