import { User } from '../User';
import { FundingReward } from './FundingReward';
import { FundingBacking } from './FundingBacking';
import { FundingUpdate } from './FundingUpdate';
import type { FundingStatus, FundingCategory } from '../../types/crowdfunding-types';
export declare class FundingProject {
    id: string;
    title: string;
    slug: string;
    description: string;
    shortDescription: string;
    category: FundingCategory;
    tags: string[];
    creatorId: string;
    creator: User;
    creatorName: string;
    creatorDescription: string;
    targetAmount: number;
    currentAmount: number;
    minimumAmount: number;
    startDate: Date;
    endDate: Date;
    estimatedDeliveryDate: Date;
    backerCount: number;
    viewCount: number;
    likeCount: number;
    shareCount: number;
    updateCount: number;
    status: FundingStatus;
    isVisible: boolean;
    isFeatured: boolean;
    isStaffPick: boolean;
    mainImage: string;
    images: string[];
    videoUrl: string;
    story: string;
    risks: string;
    allowComments: boolean;
    allowAnonymousBacking: boolean;
    showBackerList: boolean;
    approvedAt: Date;
    approvedBy: string;
    rejectionReason: string;
    rewards: FundingReward[];
    backings: FundingBacking[];
    updates: FundingUpdate[];
    createdAt: Date;
    updatedAt: Date;
}
//# sourceMappingURL=FundingProject.d.ts.map