name: Auto Deploy on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.WEB_HOST }}
        username: ${{ secrets.WEB_USER }}
        key: ${{ secrets.WEB_SSH_KEY }}
        script: |
          # 임시 디렉토리
          WORK_DIR="/tmp/deploy-$(date +%s)"
          TARGET_DIR="/var/www/admin.neture.co.kr"
          
          # 최신 코드 가져오기
          git clone --depth 1 https://github.com/Renagang21/o4o-platform.git "$WORK_DIR"
          cd "$WORK_DIR"
          
          # Node.js 설정
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22.18.0
          
          # 빌드
          pnpm install --frozen-lockfile
          pnpm run build:packages
          cd apps/admin-dashboard
          NODE_OPTIONS='--max-old-space-size=4096' \
          GENERATE_SOURCEMAP=false \
          VITE_API_URL=https://api.neture.co.kr \
          pnpm run build
          
          # 백업
          if [ -d "$TARGET_DIR" ]; then
              sudo cp -r "$TARGET_DIR" "/var/www/admin-backup/backup-$(date +%Y%m%d-%H%M%S)"
          fi
          
          # 배포
          sudo rm -rf "$TARGET_DIR"/*
          sudo cp -r dist/* "$TARGET_DIR"/
          
          # 버전 정보 추가
          TIMESTAMP=$(date +%s)
          echo "{\"version\": \"$TIMESTAMP\", \"commit\": \"${{ github.sha }}\", \"deployed\": \"$(date)\"}" | sudo tee "$TARGET_DIR/version.json" > /dev/null
          
          # 권한 설정
          sudo chown -R www-data:www-data "$TARGET_DIR"
          
          # Nginx 캐시 클리어 및 재로드
          sudo rm -rf /var/cache/nginx/*
          sudo systemctl reload nginx
          
          # 브라우저 캐시 무효화를 위한 헤더 설정
          echo "Cache cleared. Users may need to hard refresh (Ctrl+F5)"
          
          # 정리
          cd /
          rm -rf "$WORK_DIR"
          
          echo "✅ Deployment complete!"