name: 📊 Cache Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

env:
  NODE_VERSION: '22.18.0'

jobs:
  test-with-lock-file:
    name: Test with package-lock.json
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[test-cache]')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node.js with standard cache
        id: setup-with-lock
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - name: Measure install time
        id: measure-with-lock
        run: |
          START_TIME=$(date +%s)
          pnpm install --frozen-lockfile
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "duration=$DURATION" >> $GITHUB_OUTPUT
          echo "cache-hit=${{ steps.setup-with-lock.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      
      - name: Report results
        run: |
          echo "### With package-lock.json"
          echo "- Cache hit: ${{ steps.measure-with-lock.outputs.cache-hit }}"
          echo "- Install duration: ${{ steps.measure-with-lock.outputs.duration }}s"

  test-with-dependency-path:
    name: Test with cache-dependency-path
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove package-lock.json
        run: rm -f package-lock.json
      
      - name: Setup Node.js with dependency path cache
        id: setup-with-path
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      
      - name: Measure install time
        id: measure-with-path
        run: |
          START_TIME=$(date +%s)
          pnpm install
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "duration=$DURATION" >> $GITHUB_OUTPUT
          echo "cache-hit=${{ steps.setup-with-path.outputs.cache-hit }}"
      
      - name: Report results
        run: |
          echo "### With cache-dependency-path"
          echo "- Cache hit: ${{ steps.measure-with-path.outputs.cache-hit }}"
          echo "- Install duration: ${{ steps.measure-with-path.outputs.duration }}s"

  compare-results:
    name: Performance Comparison
    runs-on: ubuntu-latest
    needs: [test-with-lock-file, test-with-dependency-path]
    if: always()
    
    steps:
      - name: Generate comparison report
        run: |
          echo "## 📊 Cache Performance Comparison"
          echo ""
          echo "| Method | Cache Hit | Install Time |"
          echo "|--------|-----------|--------------|"
          echo "| package-lock.json | Check workflow | Check workflow |"
          echo "| cache-dependency-path | Check workflow | Check workflow |"
          echo ""
          echo "**Recommendation**: Generate package-lock.json for optimal performance"