name: CI Optimized

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        chmod +x ./scripts/install.sh
        ./scripts/install.sh ci
      timeout-minutes: 15
    
    - name: Build packages
      run: npm run build:packages
      timeout-minutes: 10
    
    - name: Type check
      run: npm run type-check
      timeout-minutes: 5
    
    - name: Lint
      run: npm run lint
      timeout-minutes: 5
    
    - name: Build apps
      run: npm run build:apps
      timeout-minutes: 15