name: Deploy Nginx Configuration

concurrency:
  group: deploy-nginx-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
    paths:
      - 'nginx-configs/**'
      - '.github/workflows/deploy-nginx.yml'

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Nginx configs to web server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.WEB_HOST }}
        username: ${{ secrets.WEB_USER }}
        key: ${{ secrets.WEB_SSH_KEY }}
        script: |
          # Create backup directory with timestamp
          BACKUP_DIR="/etc/nginx/backup/$(date +%Y%m%d_%H%M%S)"
          sudo mkdir -p "$BACKUP_DIR"
          
          # Backup current nginx configs
          echo "📁 Creating backup at $BACKUP_DIR"
          sudo cp -r /etc/nginx/sites-available "$BACKUP_DIR/" || true
          sudo cp -r /etc/nginx/sites-enabled "$BACKUP_DIR/" || true
          
          # Navigate to repository
          cd /home/ubuntu/o4o-platform
          
          # Pull latest changes
          echo "🔄 Pulling latest nginx configs..."
          git fetch origin
          git pull origin main
          
          # Copy nginx configs to system
          echo "📋 Deploying nginx configs..."
          sudo cp nginx-configs/admin.neture.co.kr.conf /etc/nginx/sites-available/
          sudo cp nginx-configs/neture.co.kr.conf /etc/nginx/sites-available/ || true
          sudo cp nginx-configs/api.neture.co.kr.conf /etc/nginx/sites-available/ || true
          
          # Enable sites (create symlinks)
          sudo ln -sf /etc/nginx/sites-available/admin.neture.co.kr.conf /etc/nginx/sites-enabled/ || true
          sudo ln -sf /etc/nginx/sites-available/neture.co.kr.conf /etc/nginx/sites-enabled/ || true
          sudo ln -sf /etc/nginx/sites-available/api.neture.co.kr.conf /etc/nginx/sites-enabled/ || true
          
          # Test nginx configuration
          echo "🧪 Testing nginx configuration..."
          if sudo nginx -t; then
            echo "✅ Nginx configuration test passed"
            
            # Reload nginx
            echo "🔄 Reloading nginx..."
            sudo systemctl reload nginx
            
            # Check nginx status
            if sudo systemctl is-active --quiet nginx; then
              echo "✅ Nginx reloaded successfully!"
              echo "📅 Deploy time: $(date)"
              echo "📝 Commit: $(git rev-parse HEAD)"
            else
              echo "❌ Nginx failed to reload properly"
              exit 1
            fi
          else
            echo "❌ Nginx configuration test failed!"
            echo "🔙 Rolling back to backup..."
            sudo cp -r "$BACKUP_DIR/sites-available"/* /etc/nginx/sites-available/
            sudo cp -r "$BACKUP_DIR/sites-enabled"/* /etc/nginx/sites-enabled/
            sudo systemctl reload nginx
            exit 1
          fi
          
          # Cleanup old backups (keep last 5)
          echo "🧹 Cleaning up old backups..."
          sudo find /etc/nginx/backup -type d -name "20*" | sort -r | tail -n +6 | sudo xargs rm -rf || true
          
          echo "🎉 Nginx deployment completed successfully!"