name: 🧪 Test Cache Fix

on:
  workflow_dispatch:
  push:
    branches: [ test-cache-fix ]

env:
  NODE_VERSION: '22.18.0'

jobs:
  test-without-lock:
    name: Test without package-lock.json
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove package-lock.json if exists
        run: rm -f package-lock.json
      
      - name: Setup Node.js with fixed cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Verify installation
        run: |
          echo "✅ pnpm install completed successfully"
          npm list --depth=0

  test-custom-action:
    name: Test custom safe action
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove package-lock.json if exists
        run: rm -f package-lock.json
      
      - name: Setup Node.js with safe cache
        uses: ./.github/actions/setup-node-safe
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Verify installation
        run: |
          echo "✅ pnpm install completed successfully"
          npm list --depth=0